### ISSUE TITLE
Spacing between branch is not consistent

### ISSUE THREAD

**Issue by bpatra** [nicoespeon/gitgraph.js#101]
When we have a git graph with several branches the x-space between branches is not consistent. It results on a not very nice looking graph. I do not think this is intentional.

![badbranchesspaces](https://cloud.githubusercontent.com/assets/2801702/12931397/cd0363ec-cf7d-11e5-90d0-51860c97a8c8.jpg)

**Comment by bpatra** [comment]
I have created a reproduction case on my fork to reproduce the issue https://github.com/bpatra/gitgraph.js/commit/a39e1066dd102b3d0a70fc77255f19cdc56220d5

**Comment by nicoespeon** [comment]
Hi @bpatra and thanks a lot for reporting such a detailed use case :+1:

**Comment by bpatra** [comment]
Thank you, I need this fix soon, I will try to create a PR.

**Comment by bpatra** [comment]
There is no bug, it was linked to the way I was rendering the graph using the recursive algorithm.
