### ISSUE TITLE
Option to switch off the tooltip in compact mode

### ISSUE THREAD

**Issue by beckerIGG** [nicoespeon/gitgraph.js#102]
Hi,

i would like to switchoff the tooltip in compact mode. but i do not know how. I wrote my own tooltip for extended and compact mode. but know in compact mode i have both. my own one and the gitgraph tooltip, any ideas how to swith it off in minified version?
also i couldn't bring the commit:mouseout Eventlistener to work. i used now a one directly for the canvas element. Any ideas on that?

THX
Thomas

**Comment by bpatra** [comment]
I am not sure I understand correctly. You want your tooltip to be disabled in some cases, am I right ?what about using a css class in your html tooltip with display:none ?

**Comment by beckerIGG** [comment]
Hi,

no i want to disable the gitgraph tooltip all the time. Any chance to do 
this?

BR Thomas
Am 17.03.2016 um 15:49 schrieb Benoît Patra:

**Comment by nicoespeon** [comment]
Hi @beckerIGG!

I can confirm you that, for now, tooltips automatically appear when you’re in compact mode and there is no simple way that comes to my mind to achieve what you’d like to do.

I guess we can give an option for that. I’ll let you know.

Concerning the event issue: which version of gitgraph do you use? It was recently merged but wasn’t part of a release yet (= not in `v1.1.3`).

**Comment by beckerIGG** [comment]
Hi,

i am using v.1.1.3. i will try to use the extended mode, so far.

BR Thomas
Am 17.03.2016 um 17:18 schrieb Nicolas Carlo:

**Comment by nicoespeon** [comment]
Ok, that’s why you don’t have mouseout events by the way.

I’ll add this option and do a patch release by the end of the week with all of these =)

**Comment by beckerIGG** [comment]
Thanks a lot.

BR Thomas
Am 17.03.2016 um 17:25 schrieb Nicolas Carlo:

**Comment by nicoespeon** [comment]
There you go @beckerIGG, `v1.2.0` is out with anything you need.

To disable tooltips: 

```javascript
var myTemplateConfig = {
  // … any specific template configuration
  commit: {
    shouldDisplayTooltipsInCompactMode: false // default = true
  }
};

var gitGraph = new GitGraph( { 
  template: new GitGraph.Template( myTemplateConfig ), 
  mode: "compact" 
} );

// Look ma, no tooltip over compacted commits!
```
