### ISSUE TITLE
Tag alignment 

### ISSUE THREAD

**Issue by Jayde-Im** [nicoespeon/gitgraph.js#103]
Your work is great, and I appreciate using it. 

But one little part is bothering me. 
When the font sizes of the tag and the message are different and tag name is long, the tag is not properly aligned.

I'm using this template in the latest version of gitgraph.js. (Also, latest version of Chrome)
```
var graphConfig = new GitGraph.Template({
  'colors': [ "#979797", "#008fb5", "#f1c109" ],
  'commit': {
    'message': {
      'displayBranch': false
    }
  }
});
```

And this is an example,
I apply this template to gitflowsupport.js, it looks like below.

![image](https://cloud.githubusercontent.com/assets/13883550/14044636/2544630a-f2d6-11e5-95c7-3e8365481e93.png)

The "v1.0.2-a-super-tag" tag isn't aligned with others.

Yeah, I know it's quite minor issue, but it's not pretty in my project. 
Although, this library is really good! :smile:

**Comment by nicoespeon** [comment]
Hi @Jayde-Im!

Thanks a lot for spotting out this and for the PR! 

I'll have a look, test it and get it fixed quickly ;-)
