### ISSUE TITLE
About npm version

### ISSUE THREAD

**Issue by x09326** [nicoespeon/gitgraph.js#105]
Hi, I'm an intern contributor of [cdnjs](https://cdnjs.com).

I added this lib with git auto-update on the cdnjs. https://github.com/cdnjs/cdnjs/pull/7733

But we prefer to use npm auto-update, and I notice that this lib is not the latest version on [npm](https://www.npmjs.com/package/gitgraph.js).
So can you update this lib on the npm?

Thank for your help!

**Comment by nicoespeon** [comment]
Hi @x09326!

You're right, it has been a long time I didn't publish latests versions of the lib on npm. Completely forgot that!

It's done. I'll ensure to do it for next releases too.
Thanks for pointing out and for adding the lib to cdnjs 👍
