### ISSUE TITLE
no event fired on firefox (ESR 38.5.1)

### ISSUE THREAD

**Issue by YMA-MDL** [nicoespeon/gitgraph.js#107]
I opened the exemple
![image](https://cloud.githubusercontent.com/assets/2270413/15522225/474af990-2211-11e6-9da6-aec62360ca6c.png)
Wether I go over a node or click it, I have not change of cursor style nor event fired showing up in the console (as the example should do)

**Comment by nicoespeon** [comment]
Hi @YMA-MDL and thanks for reporting.

I'll try to give it a look, probably next week 😉

**Comment by YMA-MDL** [comment]
Apparently support for event.offsetX starts at version 39 for Firefox
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX#Browser_compatibility

**Comment by nicoespeon** [comment]
Hi @YMA-MDL =)

Could you try this fiddle and tell me if it works with your version of Firefox: http://jsfiddle.net/Pnx4D/

The idea would be to fallback onto `event.layerX` if `event.offsetX` is not defined, but I would like to unsure it would work before giving it a try… and my Firefox browser is already v43 😄 

Thanks a lot!

**Comment by YMA-MDL** [comment]
Yes the jsfiddle works. 
(for the moment I've made a quick fix for a presentation)
![image](https://cloud.githubusercontent.com/assets/2270413/15825172/f9640482-2c02-11e6-86b4-92820b48ad32.png)

**Comment by nicoespeon** [comment]
Hi @YMA-MDL!

I made a fix on the `fix-hover-event-firefox` branch. Try it out and tell me. 
I'll release it with a new patch if it works for you 😉

**Comment by nicoespeon** [comment]
I suppose it's working as a fallback for older FF since the fiddle worked.
So I'll push it to the next patch of gitgraph.js.

Thanks again for reporting 👍
