### ISSUE TITLE
How to get data for drawing the graph

### ISSUE THREAD

**Issue by sanskar-modi** [nicoespeon/gitgraph.js#108]
It's not an issue. I want to ask how i get data for plotting the graph. I want to plot graph for a local repository for a side project. I could get commit data using `git log` and parse `git reflog` or `git --graph` output but i think their should be a better way than this. It would be better if you add this in documentation. Thanks

**Comment by nicoespeon** [comment]
Hi @sanskar-modi!

Unfortunately there is no current way to "import data" from an existing git project to rebuild the graph automatically. This is a feature we planned to do with #38.

Yet there is no much maintenance activity recently on this project so I can't promise you this will be released anytime soon.

Still, feel free to propose a PR if you are in the mood of developing this =)
