### ISSUE TITLE
Tooltips don't respect messages display options

### ISSUE THREAD

**Issue by davetrollope** [nicoespeon/gitgraph.js#119]
Hovering over a commit that was created with:

master.commit({messageDisplay:false})

still displays the default messages.

I propose showCommitTooltip() be updated to check commit.messageDisplay():
        if(commit.messageDisplay) {
          self.tooltip.textContent = commit.sha1 + " - " + commit.message;
        } else {
          self.tooltip.textContent = commit.sha1
        }

This likely isn't a full solution since it should probably respect messageHashDisplay as Commit.prototype.render does.

**Comment by nicoespeon** [comment]
Hi @davetrollope and thanks for pointing this out.

Indeed, the way tooltips display message isn't bound to commit messages, which can lead to confusion.

I'll give it a look when I have some times. It should be quick to fix and get something a bit more consistent.

**Comment by davetrollope** [comment]
I just realized that toggling messageDisplay to control tooltips will likely create ugly displays on the page - this might just need a separate set of tooltipDisplay options perhaps?

**Comment by nicoespeon** [comment]
The thing is that you can already provide a tooltip formatter to control how tooltip will look like: https://github.com/nicoespeon/gitgraph.js/blob/develop/examples/index.js#L23-L25

The only point missing is the ability to disable tooltip display in compact mode.

You pointed out that it should follow `messageDisplay` options but, as you said, it may not be the best idea.

So yep, we can add a `tooltipDisplay` options to control whether or not a tooltip will be displayed.
`messageDisplay` was introduced so people can draw an expanded graph without displaying default messages, focusing on the graph only. I guess we can think the same for tooltips in case you just want to focus on the graph, not commit messages.

So I'm going to implement a `tooltipDisplay` options that will do the same than `messageDisplay`, but for tooltips.

Did I miss something?

**Comment by davetrollope** [comment]
sounds good! I'm new to gitgraphs so I'm still learning the full extent of what it can and can't do...

**Comment by nicoespeon** [comment]
This is done and part of [v1.4.0](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.4.0) 👍
