### ISSUE TITLE
Issue in complex graph drawing

### ISSUE THREAD

**Issue by ASMfreaK** [nicoespeon/gitgraph.js#120]
I was generating graph from my git repo with a preety dumb python script [look at this gist here](https://gist.github.com/ASMfreaK/dbd0360ea1908857a306fb29c675ff6c). It outputs [a script](https://gist.github.com/ASMfreaK/dbd0360ea1908857a306fb29c675ff6c#file-scipt-js)
When loaded via `python -m http.server` with page, taken from examples, it stumles on [this line](https://github.com/nicoespeon/gitgraph.js/blob/develop/src/gitgraph.js#L631) with path `undefined`. Making it continue on undefined path helps, but the output contins some artifacts like these:
![_069](https://cloud.githubusercontent.com/assets/3578982/18410912/0f3acd5a-7775-11e6-83fd-458846d69d76.png)
![_070](https://cloud.githubusercontent.com/assets/3578982/18410913/11daf45e-7775-11e6-8dd2-0de567a4043a.png)

Any help?

**Comment by nicoespeon** [comment]
Thanks for this detailed issue @ASMfreaK 👍 

For what I tested so far, it seems that this scenario is causing troubles:

```javascript
var gitGraph = new GitGraph( config );
var master = gitGraph.branch("master");
master.commit();

var branch0 = master.branch("branch0");
branch0.commit().commit();

var branch1 = branch0.branch("branch1");
// branch1.commit(); // -> if is commented out, graph doesn't render properly
var branch2 = branch1.branch("branch2");
branch2.commit();
```

I'll create an issue for this. After fixing that I'll have a second look at the whole issue.

**Comment by nicoespeon** [comment]
Hi @ASMfreaK!

As of [v1.8.1](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.8.1), such complex graphs should be render properly.

Do not hesitate to open another issue if you do find other situations that are causing troubles to render.
Thanks again!

**Comment by ASMfreaK** [comment]
Thank you.
