### ISSUE TITLE
Support multiple branch parents

### ISSUE THREAD

**Issue by rixx** [nicoespeon/gitgraph.js#124]
Sometimes you want to create a branch from two other branches in the same commit.

```GithHub
git checkout parent_1
git checkout -b new_branch
git merge --no-ff parent_2
```

**Comment by nicoespeon** [comment]
Hi @rixx!

Isn't that something you could already do using merge, just like you did in your git snippet?

**Comment by rixx** [comment]
erm, yes. Not quite sure what I was getting at there because that's exactly how I've solved it in my demo. Sorry for the bother.

**Comment by nicoespeon** [comment]
No problem, thanks! 😉
