### ISSUE TITLE
Configure commits default options in branch (e.g. setting a branch color)

### ISSUE THREAD

**Issue by FogiaFr** [nicoespeon/gitgraph.js#126]
Is it possible to set a branch color (commit nodes and branch name) when declaring a branch ?

For example, with something like this:

var dev = gitgraph.branch({
        parentBranch: master,
        labelColor: "cyan",
        name: "dev",
        showLabel: true,
        column: 2
    });

The purpose is having the same color for functional alike branches (eg purple for feature branches, yellow for develop branch, cyan for master branch and so on)

**Comment by nicoespeon** [comment]
Hi @FogiaFr!

Sure, try the following:

```
var dev = gitgraph.branch({
  parentBranch: master,
  labelColor: "cyan",
  name: "dev",
  showLabel: true,
  column: 2
});
```

**Comment by FogiaFr** [comment]
Hello @nicoespeon and thanks for your fast reply.

I copy/pasted the code and the "cyan" color is ignored and the branch is displayed in green.
I am using version 1.4.0 (latest release I am aware of).

**Comment by nicoespeon** [comment]
Hmmm that's strange. 

Could you copy/paste the whole snippet of code that you have?
I'll try to figure out what's going on.

Thanks.

**Comment by FogiaFr** [comment]
Sure. I made a very simple example:

`
    var gitgraph = new GitGraph({
        template: "blackarrow",
        reverseArrow: false,
        orientation: "vertical",
        mode: "extended",
        author: "me@home.com"
    });

    var master = gitgraph.branch({
        name: "master",
        labelColor: "cyan",
        showLabel: true,
        column: 2
    });
    var develop = gitgraph.branch({
        name: "develop",
        labelColor: "yellow",
        showLabel: true,
        column: 1
    });
	
	master.commit("init");
	develop.commit("test");`

By default, the first branch is in cyan and the second in green. So I tried to override these color with yellow for the first branch and cyan for the second.
But when I open it in a brower, the first branch remains in cyan and the second in green.

**Comment by FogiaFr** [comment]
Sorry, didn't see it was color and not labelColor.

The problem with using 'color' is that the commit nodes and the branch label remain of their original color but the branch line is changed.

The black line for all branches are fine for me. What I want to change color is branch label and commit nodes (the circles) of the branch.

**Comment by nicoespeon** [comment]
Understand 👌 

Unfortunately I don't think there is an option to configure all commits of a given branch, as far as I remember.

For now you will need to pass the `color` option to each commit you want to customize: 

```javascript
dev
  .commit({ 
    color: "cyan", 
    message: "My commit message" 
  })
  .commit({ 
    color: "cyan", 
    message: "This is another commit" 
  });
```

This is not ideal 😕 

I'll keep your issue open as a suggestion to provide the ability to configure branch commits when you declare the branch, which will be way more convenient 😃

**Comment by fabien0102** [comment]
Not ideal too, but you can play with the template to set branch colors 😉 

For example:
http://codepen.io/fabien0102/pen/vyZMgY

**Comment by nicoespeon** [comment]
@fabien0102 👌 

I thought about this one, but I think that would be tricky to match @FogiaFr requirements:

> The purpose is having the same color for functional alike branches (eg purple for feature branches, yellow for develop branch, cyan for master branch and so on)

Using template, you will need to have these "functional alike branches" at the same column, which could be hacky 😆 

But that's a great solution to customize branches colors easily.

**Comment by fabien0102** [comment]
I’d said "not ideal" ^^

**Comment by nicoespeon** [comment]
Hi @FogiaFr!

As of [v1.7.0](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.7.0) you can now do:

```javascript
var dev = gitgraph.branch({
  parentBranch: master,
  color: "cyan",
  name: "dev",
  showLabel: true,
  column: 2,
  commitDefaultOptions: {
    color: "cyan"
  }
});
```

This should work as you'd expect. Let me know if you have any trouble.
