### ISSUE TITLE
Template 'blackarrow' generates orphaned arrow head

### ISSUE THREAD

**Issue by lucasvc** [nicoespeon/gitgraph.js#127]
Using version 1.4.0 and the following script:

````
var gitgraph = new GitGraph({
	template : "blackarrow",
	orientation : "vertical",
	mode : "extended",
	elementId : "graph",
});
gitgraph.template.commit.tooltipDisplay = true

var master = gitgraph.branch("master");
var develop = gitgraph.branch("develop");

function by(author, message) {
	return {
		message : message,
		author : author,
	}
}

develop.commit(by("Lucas")).commit(by("Irene"));

develop.commit({
	author : "Joan",
	tag : "other_01"
})

var other = develop.branch("other");

develop.commit(by("Irene"))

other.commit(by("Irene"))
other.merge(develop, by("Irene"))
````

I got the following graph, which commit 80309be (in the image) has an incorrect headed arrow:
![image](https://cloud.githubusercontent.com/assets/1053448/20623785/9fd2110a-b309-11e6-8b29-e972f63491e0.png)

**Comment by nicoespeon** [comment]
Hi @lucasvc, thanks for this detailed bug report, that will ease resolution a lot 👍

**Comment by nicoespeon** [comment]
Hi @lucasvc!

As of [v1.7.1](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.7.1), this should now be fixed.
Let me know if you still have troubles 😉

**Comment by lucasvc** [comment]
Thanks for the update!
But,... the rest of the script is not working now :( I'll try to see where it fails and I'll report in case.

**Comment by nicoespeon** [comment]
If you need to, don't hesitate to fork from [this fiddle](http://codepen.io/nicoespeon/pen/WoPJYe) with the rest of your script to share what's wrong with v1.7.1 😉
