### ISSUE TITLE
Canvas event handlers cannot be disposed from the consumer end

### ISSUE THREAD

**Issue by Giridharan2112** [nicoespeon/gitgraph.js#128]
Hi,
    We are working on using this library to render the gitGraph for the git history in our ALM solution. In that we are need to update the graph as and when we update the history list. Since we are in need to create new gitGraph objects, the old objects are not getting cleaned up by the GC since the canvas event handlers are not removed. We are not able to remove them from our end too. I have made minimal change to expose a function called dispose which would remove these event handlers. Are you open to accepting changes for this issue? If so I will go ahead and create a pull request.

**Comment by nicoespeon** [comment]
I understand the need to dispose event handlers so if you have a PR to implement this enhancement, I'd gladly review it.

Furthermore, your case is interesting, it reminds me a lot about #38 − related to #117. I'd like to hear more about how you did to render the full git history, while the library doesn't support this feature for now.

**Comment by Giridharan2112** [comment]
Yes, I have a the changes for this too. Will create the PR.

**Comment by Giridharan2112** [comment]
Have created a PR #131

**Comment by nicoespeon** [comment]
Thanks for this one @Giridharan2112 👍 
I'll make a release after looking / merging #130.

**Comment by Giridharan2112** [comment]
@nicoespeon , Thanks a lot for the support!
