### ISSUE TITLE
Dashed-style commits

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#139]
It would be nice to provide a way to draw dashed-style commits, like git GUIs do to illustrate WIP changes.

See #136.

**Comment by MetaiR** [comment]
does it finish yet?

**Comment by nicoespeon** [comment]
Sorry @MetaiR but it wasn't implemented yet.

Issue will be closed when this will work =)

**Comment by nicoespeon** [comment]
Hi @MetaiR!

As of [v1.11.0](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.11.0), you can draw dashed-style commits.

Hence, you can simulate a WIP commit:

```js
master.commit({
  lineDash: [3, 2],
  dotStrokeWidth: 5,
  dotColor: "white",
  messageHashDisplay: false,
  messageAuthorDisplay: false,
  message: "Current WIP",
  tag: "HEAD",
  displayTagBox: false
});
```

<img width="807" alt="wip commit" src="https://cloud.githubusercontent.com/assets/1094774/25292587/10e2e2b6-26d7-11e7-9942-f0d2dcb64387.png">

**Comment by MetaiR** [comment]
if the line of dash circle is dash either, will be better.

**Comment by nicoespeon** [comment]
I thought about it. Unfortunately, this is not something that can be easily implemented because of the current modelisation of gitgraph.js − as I explained in issue #142:

> Branches should be tags that reference a commit, so we can retrieve it (and its ancestors). Graph content should just be a collection of commits that are related each others − a graph, basically.
But for now, gitgraph.js is made of branches that contains a list of commits. Branches are "physical" things that hold a list of unrelated commits.

You can create a branch that will have a dashed style too, but it will look like another branch, which is not better for what you'd like to achieve.
There is a lot of re-work to do to make that kind of things natural.

To paraphrase myself again, I'd say:

> So my point is: good news, that's where the project is moving to.
> The bad news is that it may take me some time to have something as complete as the current version. I may ship something when it will be good enough to address concerns the current version doesn't. But that will probably be a major version upgrade, with breaking changes.

**Comment by MetaiR** [comment]
so many thanks :)
