### ISSUE TITLE
Multiple labels at same commit

### ISSUE THREAD

**Issue by JKrag** [nicoespeon/gitgraph.js#143]
I would love to be able to have multiple branch labels pointing to the same commit. This is a very common occurrence in Git, the most obvious cases being:

- Just after creating a new branch
- remote tracking branches

The following example (see #142 for details) shows `foo` and `bar`referencing the same commit.

![image](https://cloud.githubusercontent.com/assets/1712950/22506562/64ccef0a-e881-11e6-8701-46bd9c76045e.png)

[](http://learngitbranching.js.org/) also supports this nicely with a slightly different rendering:
![image](https://cloud.githubusercontent.com/assets/1712950/22506626/c6f20850-e881-11e6-993a-5bc3affa1f9b.png)

**Comment by nicoespeon** [comment]
So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and this was kinda implemented here:

![image](https://user-images.githubusercontent.com/1094774/52529173-58b0d080-2cbb-11e9-9d01-6abc120b62eb.png)

```jsx
<Gitgraph>
  {(gitgraph) => {
    const master = gitgraph.branch("master");
    master
      .commit()
      .tag("v1.0")
      .tag("first-release")
      .tag("epic");
  }}
</Gitgraph>
```

Now, tags are currently rendered as part of the commit message, just like branch. But we'll probably change that in further releases, so we can have something that looks more like previous screenshots. Nevertheless, you can now set multiple tags on the same commit.

Thus, I'm closing this issue as we won't maintain the `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. 

We still accept PRs if someone really needs it, but I'd suggest moving to the aforementioned packages. Thanks 🙏
