### ISSUE TITLE
Render forks

### ISSUE THREAD

**Issue by iluwatar** [nicoespeon/gitgraph.js#144]
I read through the documentation but came to conclusion that gitgraph.js only supports single repository / multiple branches. Would it be possible to visualize at least 2 repositories which is common in forking workflow?

**Comment by nicoespeon** [comment]
Current implementation is designed to represent a single repo indeed. Actually, there is no notion of repo at all.

I guess the use case would look like GitHub's network, right?

<img width="660" alt="multi-repo-gitgraph" src="https://cloud.githubusercontent.com/assets/1094774/22682637/07a8b8a8-ed14-11e6-8a81-54e5d4b4f229.png">

I understand the use case. Though I don't want to overload the library with very specific use cases if that means to make things harder for basic use cases. I need to figure out the best way to do that.

I keep the suggestion open so I can make my mind around this idea, but I don't think it will be implemented soon as I'm working on different issues for the moment.

**Comment by nicoespeon** [comment]
Closing this one as it's still out of the scope of the library. Thanks for proposing though 👍
