### ISSUE TITLE
Positioning of commit details vary from version 1.0.3 to Version 1.8.3

### ISSUE THREAD

**Issue by molikmiah** [nicoespeon/gitgraph.js#145]
The detailed sections on different branches are not vertically aligned correctly. Please see attached screenshots for version 1.0.3 and version 1.8.3.

**Version 1.0.3:**
![version 1 0 3](https://cloud.githubusercontent.com/assets/10675007/23410225/63440dbc-fdc6-11e6-8301-c0cd79432af3.png)

**Version 1.8.3**
![version 1 8 3](https://cloud.githubusercontent.com/assets/10675007/23410239/6ef643b4-fdc6-11e6-947d-3a4917465518.png)

**Comment by nicoespeon** [comment]
Thanks for reporting this issue @molikmiah 👍

**Comment by nicoespeon** [comment]
FYI, this fix is part of [release v1.10.1](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.10.1).
