### ISSUE TITLE
Configurable tooltip container

### ISSUE THREAD

**Issue by klebba** [nicoespeon/gitgraph.js#147]
It's not always the case that the tooltip element should be appended the document body. It would be useful to allow the developer to override this default with a provided element target. Thanks for considering!

**Comment by nicoespeon** [comment]
That's a good point, thanks for suggestion 👍

**Comment by nicoespeon** [comment]
Hi @klebba!

As of [v1.9.0](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.9.0) you can specify a custom HTML element to contain tooltips displayed in compact mode:

```javascript
var gitGraph = new GitGraph({
  template: "metro",
  tooltipContainer: document.querySelector("#tooltips"),
  mode: "compact"
});
```

If you don't provide a `tooltipContainer`, it will default to `document.body`.

**Comment by klebba** [comment]
Cool!
