### ISSUE TITLE
Customize tag text color + font

### ISSUE THREAD

**Issue by nathan-alden** [nicoespeon/gitgraph.js#151]
Branch colors that look good on white backgrounds tend to be darker colors. Unfortunately, it seems the tag text color is always black, so it can become hard to read the tag colors. Optimally, there would be two sets of colors--perhaps something like this:
```
var template = GitGraph.prototype.newTemplate("metro");
        
template.branchColors = [ "FireBrick", "SeaGreen", "DodgerBlue", "DarkViolet" ];
template.tagColors = [ "White", "White", "White", "White" ];
```

**Comment by nicoespeon** [comment]
Hi @nathan-alden!

Indeed, tags background color follows commit's one. 
You can individually select a specific background color using `.tag({ tag: "v1.0", tagColor: "white" })`, but there is no possibility to configure this at template level for now.

Just to be sure: are you suggesting to configure the tag background color or the tag text color, keeping the current implementation for the background color?

In either case, this is addressing a current problem with tags that needs to be considered.

**Comment by nathan-alden** [comment]
I am suggesting changing the tag's foreground color. Right now it's always black, which interferes with common branch colors.

**Comment by nicoespeon** [comment]
👍 Thanks for clarification.
