### ISSUE TITLE
Turn js file to smaller js files

### ISSUE THREAD

**Issue by MetaiR** [nicoespeon/gitgraph.js#156]
I saw this on the famous projects like [materialize](https://github.com/Dogfalo/materialize).

they turned their js file to smaller files and this makes developing so easier.

can you do something like that?

**Comment by nicoespeon** [comment]
Hi @MetaiR!

Yup, you're completely right. This is something we should do to make the code more maintainable.

**Comment by nicoespeon** [comment]
Closing this issue since it'll be resolved with #187. 🙌
