### ISSUE TITLE
Detail HTML is not made visible when injected into DOM

### ISSUE THREAD

**Issue by JonathanRowley** [nicoespeon/gitgraph.js#157]
Using Angular and *ngFor in HTML template for commit detail content doesn't appear.
```html
<div id="test-{{ item.id }}" *ngFor="let item of items" class="gitgraph-detail"></div> 
```

```js
someBranch.commit({
     detailId: 'test-' + item.id
})
````

tested with: vertical orientation and expanded mode

**Comment by fabien0102** [comment]
Angular have a shadow dom processing, try to put gitgraph part into "onRender/afterRender" angular hook (I don't know the name of the hook, I let you look into angular doc #livecycle)

You need to have DOM render before use gitgraph ;) or you can trigger a gitgraph.render() manually after DOM rendering 

Note: I'm on my phone, so I don't have the doc easily ^^ If you want more details, please do a codepen with your usecase ;)

**Comment by fabien0102** [comment]
http://plnkr.co/edit/PIxqMlEkn1DbFhgqrQpF?p=preview

Tadaaaaaaa! So yeah, just put your code into `ngAfterViewInit()` hook 😉

**Comment by nicoespeon** [comment]
Thanks @fabien0102 👌 

@JonathanRowley let us know if there is something we missed. Until then, I'm closing this issue as of Fabien's answer.
