### ISSUE TITLE
Graph rendering fails with basic branching

### ISSUE THREAD

**Issue by laymain** [nicoespeon/gitgraph.js#159]
Hi,

There's a bug on the graph rendering when a commit is made on a branch
after it has been used to create another branch:

![image](https://cloud.githubusercontent.com/assets/389065/25738233/3052e39e-317c-11e7-8fdb-97adff269c63.png)

```javascript
var graph1 = new GitGraph({
  elementId: 'badGraph',
  mode: 'compact',
  template: 'blackarrow'
});
var m1 = graph1
  .branch("master")
  .commit();
var r1 = m1
  .branch('1.0.x');
m1.commit();
r1
  .commit()
  .merge(m1);
```

If we do the commit on the new branch before the commit on the first one, it renders finely:

![image](https://cloud.githubusercontent.com/assets/389065/25738270/64b4a7f8-317c-11e7-9f6b-ab2c2b43abab.png)

```javascript
var graph0 = new GitGraph({
  elementId: 'workingGraph',
  mode: 'compact',
  template: 'blackarrow'
});
var m0 = graph0
  .branch("master")
  .commit();
var r0 = m0
  .branch('1.0.x')
  .commit();
m0.commit();
r0.merge(m0);
```

https://jsfiddle.net/Laymain/k0z0277g/

**Comment by nicoespeon** [comment]
Hi @laymain, thanks for pointing out this issue, this is definitely a bug!

**Comment by yodalee** [comment]
I think this is related to the PR I push, I will dig into this issue.

**Comment by yodalee** [comment]
I take some time to trace the bug, at least in tag v1.1.0, the output graph is still OK, I will use bisect to see where goes wrong.

**Comment by yodalee** [comment]
Rough tracing takes me to cc8110f04971f95ac90833ff65bab00181fe84bb
This commit cause the arrow start at first commit

**Comment by nicoespeon** [comment]
Hi @laymain,

Thanks to @yodalee, this should be fixed with v1.11.4 (https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.11.4).

**Comment by laymain** [comment]
Hi,

The wrong arrow angle is fixed, that's nice.
But is there any reason why it does not render in the same way
if a commit is made before or after branching?

![image](https://user-images.githubusercontent.com/389065/29109585-d0588d5a-7ce3-11e7-946b-ae2e841f1acc.png)

**Comment by nicoespeon** [comment]
I guess the reason is that rendering scenario doesn't take the same path and happen to follow a different strategy, which lack consistency.

Hopefully, that doesn't seem to be a big deal. But that is not expected.
I created another issue for this: https://github.com/nicoespeon/gitgraph.js/issues/174

Thanks 😉
