### ISSUE TITLE
Create a branch at specific commit

### ISSUE THREAD

**Issue by SmallhillCZ** [nicoespeon/gitgraph.js#162]
Suppose I made a branch from some commit in the past, like this:
```
A
|\
B |
| |
C |
| |
| D
|/
E
```

How do you do this in this library? Thanks for advice!

// I made a little wizard/script to graph GitHub repository (https://smallhillcz.github.io/githgraph-js-auto/) and this is my last missing feature. Currently it ends up like:
```
A
|
B
|
C
|\
| D
|/
E
```

Moreover sometimes one would even need to merge from past commit:

```
A
|\
| \
B  |
|\ C
D \|
|  E
| /
|/
F
```

**Comment by nicoespeon** [comment]
Hi @SmallhillCZ,

Currently, the only way to achieve this would be to create the second branch just after the A commit. Like this:

```js
var gitGraph = new GitGraph({
  template: "blackarrow",
  reverseArrow: false,
  orientation: "vertical"
});

var master = gitGraph.branch("master");

master.commit({ message: "A" });

develop = master.branch("develop");

master
  .commit({ message: "B" })
  .commit({ message: "C" });

develop.commit({ message: "D" });

develop.merge(master, { message: "E" });
```

However, we should be able to point a commit directly. So I'm tagging this as a "feature" to be implemented.
