### ISSUE TITLE
Feature Request: Make branch labels absolute positioned divs

### ISSUE THREAD

**Issue by omarzion** [nicoespeon/gitgraph.js#170]
Making the branch labels divs so they can be styled, or adding template options for them like there are for message: would be nice
either
```
.gitgraph-branch-label {
 border: 2px solid black;
 font-size: 2em;
}
```
or
```
branch {
 showLabel: true,
 label: {
  font: 'normal 12pt Arial';
  border: 'none'
 }
}
```

**Comment by nicoespeon** [comment]
Hi @omarzion,

Would #151 solve this issue? It looks like it's related to me.

**Comment by omarzion** [comment]
Hi @nicoespeon 

I think #151 and adding a font property like you have for commit messages would solve the problem.

The idea I had with making it a div was the ability to have the branch labels move up and down the branch when scrolling to stay in view while you could still see the branch, but that would probably be a lot of reworking for little gain

**Comment by nicoespeon** [comment]
Agreed, I updated the issue title to take font property into account.

I'll let you know when this is done on this issue then. Thanks for clarifying 👍
