### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by atanasyanew** [nicoespeon/gitgraph.js#172]
Hi. is there a way to display tooltips now only for compact mode. 
For the first picture i have my graph but without the tooltip.
Second picture have tooltip, i tried many different ways to implement it but only works when the mode is compact.
Thanks

![1](https://user-images.githubusercontent.com/21058194/28501818-bbb25650-6fec-11e7-81a6-f608e342bded.JPG)

![2](https://user-images.githubusercontent.com/21058194/28501819-bbb44eb0-6fec-11e7-81f3-2218173f51f9.JPG)

**Comment by nicoespeon** [comment]
Hi @atanasyanew,

Indeed, tooltips only appear when messages are not displayed − they were meant to replace message, notably in "compact mode" (picture 2).

Question: why would you need the tooltip when message are displayed. Wouldn't both be redundant?

**Comment by nicoespeon** [comment]
Closing stale issue.

**Comment by JohnnyJumper** [comment]
I think it can be beneficial to allow tooltips with messages. You can format tooltip to behave as a hint for example. Give more functionality
