### ISSUE TITLE
Draw line or arrow between tag and commit

### ISSUE THREAD

**Issue by jessetan** [nicoespeon/gitgraph.js#173]
If a commit has been tagged, the tag is displayed to the right of the commit in vertical mode and below the commit in horizontal mode. If there are many branches, or the tag name is long (especially in horizontal mode) it can be hard to see which commit was tagged.
It could help if there was an error from the tag to the commit or a dashed line (e.g. vertical line in horizontal mode) to more clearly show where on the branch the commit is placed.

Examples:
![](https://meteo.unican.es/trac/raw-attachment/blog/git/git-workflow-release-cycle-1historical.png)
![](https://cdn-images-1.medium.com/max/1600/1*cf1L-J-hEr8seSKLn9uHwQ.png)

**Comment by nicoespeon** [comment]
Tags are no more rendered in horizontal mode. We need to find a better way to display them here, and I'm taking your suggestions as inputs, they look great 👌 

Closing this issue in favor of #237 then.
