### ISSUE TITLE
possible to display tags next to commit

### ISSUE THREAD

**Issue by ruddhardesty** [nicoespeon/gitgraph.js#176]
hi - I'm trying to figure out how to get the tags to appear next to the commits, rather than just below the baseline.  Here is what I am seeing:
![image](https://user-images.githubusercontent.com/8784147/29835576-5153e60c-8ca7-11e7-9569-d33e3fe45002.png)

what I was hoping to accomplish:
![image](https://user-images.githubusercontent.com/8784147/29835679-96263924-8ca7-11e7-99a6-1d24a0db8383.png)

In "  function Tag(commit, options) {", i played around with 

var tagColumn = (commit.parent.columnMax + 1);

changing it to "commit.parent.column", but that didn't have the expected results.

If this is possible, i can't find how to do it.  If not currently possible, then this is a suggestion for an enhancement.

Thanks!

**Comment by MrKieren** [comment]
I got this working for horizontal diagrams with the following change:

```
if (_isHorizontal(commit.parent)) {
    x = commit.x - commit.dotSize / 2;
    y = (commit.branch.column * commit.template.commit.tag.spacingY) + commit.template.commit.tag.spacingY / 2;
}
```

**Comment by ruddhardesty** [comment]
Thanks!  that accomplishes what I was trying to do.

I also see issue #173, which has a similar goal.
