### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContext' of undefined

### ISSUE THREAD

**Issue by bitbythecron** [nicoespeon/gitgraph.js#182]
I'm using the following HTML file and when I open it in a browser I see blank/empty web page:

```
<html>
  <head>
    <title>GitFlow</title>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/gitgraph.js/1.11.4/gitgraph.css" />
  </head>
  <body>
    <canvas id="gitGraph"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gitgraph.js/1.11.4/gitgraph.min.js"></script>
    <script>
      var gitgraph = new GitGraph({
        template: "blackarrow",
        reverseArrow: false,
        orientation: "horizontal",
        mode: "compact"
      });
    </script>
  </body>
</html>
```

When I open developer tools I see the following console error:

    Uncaught TypeError: Cannot read property 'getContext' of undefined

**Any ideas what the fix is?**

**Comment by fabien0102** [comment]
mmm, try to put the script after the canvas declaration ;)

**Comment by bitbythecron** [comment]
Thanks @fabien0102 -- please see my updates, I tried your suggestion and still the exact same problem, any ideas? Thanks again!

**Comment by fabien0102** [comment]
@bitbythecron It's working perfectly with your updated script, but you need to add some branchs/commits to show 😄 

Try to add `gitgraph.branch().commit().commit();` for example :wink:

**Comment by nicoespeon** [comment]
Hi @bitbythecron 👋 

Do you still have the problem, even after trying @fabien0102's suggestion?

**Comment by rwhiten1** [comment]
FWIW, I was having the exact same problem described by @bitbythecron and this suggestion:

>mmm, try to put the script after the canvas declaration ;)

Fixed it for me.

**Comment by nicoespeon** [comment]
Thanks for the feedback @rwhiten1 👍 
I consider the issue closed then.
