### ISSUE TITLE
Export graphs to image file?

### ISSUE THREAD

**Issue by zharvey-welltok** [nicoespeon/gitgraph.js#183]
Is it possible to export these "*GitGraphs*" as images (PNG, JPG even PDF)? I didn't see any evidence in the docs but I could have missed something.

Unless anybody has any better ideas I'm thinking that I'll just need to take a screenshot of the final graph (from inside my browser), although that feels a little hacky! Thanks for any-and-all input/steering!

**Comment by fabien0102** [comment]
Screenshot seems to be the better solution ^^ and you can print as a PDF for the PDF export :wink:

It's just totally out of the scope of this library :wink:

**Comment by nicoespeon** [comment]
In addition to what @fabien0102 said: exporting graphes as images may be done with an extension of the lib, but that's indeed not the goal of the core lib.

Furthermore, we are not actively maintaining the library for now, so I'd go for a screenshot solution too 👍 

I'm closing this but feel free to ask if you have any further question.
