### ISSUE TITLE
Merge gives Uncaught TypeError: Cannot read property 'y' of null

### ISSUE THREAD

**Issue by brampat** [nicoespeon/gitgraph.js#184]
When I do "master.merge(local_master, "Merge");" I get the above JS error. Am I doing something wrong?

Code:
```
var templateConfig = {
  colors: [ "#e842f4", "#f4e241", "#20aa19", "#18a9a0" ],
  branch: {
    lineWidth: 8,
    spacingX: 50,
    showLabel: true,                  // display branch names on graph
  },
  commit: {
    spacingY: -40,
    dot: {
      size: 12
    },
    message: {
      displayAuthor: false,
      displayBranch: false,
      displayHash: false,
      font: "normal 12pt Arial"
    },
    shouldDisplayTooltipsInCompactMode: false, // default = true
    tooltipHTMLFormatter: function ( commit ) {
      return "" + commit.sha1 + "" + ": " + commit.message;
    }
  }
};
var template = new GitGraph.Template( templateConfig );


var gitgraph = new GitGraph({
    template: template,
//    template: "metro",
//    orientation: "horizontal",
    mode: "compact",
    author: "Bram",

});
var local_master = gitgraph.branch("local_master");
var master = gitgraph.branch("Remote_master");
master.commit("Work");
master.commit("Work");
master.merge(local_master, "Merge");
local_master.commit("Work");
```

**Comment by brampat** [comment]
Also, is there a way to display commits on different branches on the same X or Y coordinate? In the docs, where example pics are given for the blackarrow and metro templates, the commits directly after the split are on the same x-coordinates.

**Comment by fabien0102** [comment]
It's seams to have a bug, try to add a commit on the local_master before the merge and it's works :wink:
For have the same X, it's already here, it just depend of the order of your history

```js
var local_master = gitgraph.branch("local_master").commit(); // to fix your bug
var master = gitgraph.branch("Remote_master");
master.commit("Work");
local_master.commit(); // should be on the same X as a `master` commit ;)
master.commit("Work");
master.merge(local_master, "Merge");
local_master.commit("Work");
```

**Comment by brampat** [comment]
@fabien0102 Thanks, so I guess it's not possible to to a merge (as pointed out in Chrome's dev-console) to do a merge when the org branch has no intermediate commit? Okay.

As for same x-coords: I've been fiddling a bit with orders and noticed this does make it sometimes possible to align commits on the same X. I'll fiddle some more to see if I can get it to work.

Thanks again.
