### ISSUE TITLE
Cannot read property 'color' of undefined

### ISSUE THREAD

**Issue by denpatin** [nicoespeon/gitgraph.js#185]
The original issue comes from Gitea: https://github.com/go-gitea/gitea/issues/3382

But still I'm duplicating the text:

## Description

There're not so many branches that a currently simultaneously used (around 6-7), however the overall number of branches is 28. Something started to go wrong today then the git graph stopped to display correctly—there're no more colors at all. Below are the screenshots of the problem.

Unfortunately I really cannot give more info about the problem because our development process haven't changed for a long time: We just commit and push and very often review this git graph on out instance of Gitea. And out of the blue it gets white with an error in JS console.

My first assumption was that it may be connected with the fact than each new branch gets it own color, and maybe there's a finite number of colors to display, however 28 branches isn't a limit at all for a bit project... So I do believe the assumption is wrong.

## Screenshots

The result of something goes wrong with git graph:

![image](https://user-images.githubusercontent.com/1271040/34992008-b5b54e76-fadc-11e7-89bc-8bc6ed479518.png)

What the developer tools in Chrome outputs regarding the error:

![image](https://user-images.githubusercontent.com/1271040/34992127-2f0d71ae-fadd-11e7-9e7f-d5bccda94644.png)

The direct place in the JS file where the error occurs:

![image](https://user-images.githubusercontent.com/1271040/34992371-116d74e0-fade-11e7-8bc9-3e1879c88da0.png)

**Comment by denpatin** [comment]
As said [here](https://github.com/go-gitea/gitea/issues/3382#issuecomment-358249504), this isn't an appropriate repo for the issue. So I close it.

**Comment by nicoespeon** [comment]
No problem @denpatin. Actually that's interesting, I didn't knew there was another "gitgraph.js" project.

Sorry for the confusion. Hope you problem will be solved 😉

**Comment by denpatin** [comment]
@nicoespeon Yours has much more stars so I thought it's more relevant :)
