### ISSUE TITLE
Is it possible to sort commits tree by date?

### ISSUE THREAD

**Issue by caracal7** [nicoespeon/gitgraph.js#191]

**Comment by fabien0102** [comment]
I don't have your point, by nature commits are sorted by date 🤔

**Comment by caracal7** [comment]
Oppps... This is my mistake...
Everything seem to be ok.
![2018-03-08 13 52 15](https://user-images.githubusercontent.com/5710103/37147458-09ab03ae-22d8-11e8-987a-a93ebe7d77ec.png)

Thanks)

**Comment by fabien0102** [comment]
Your welcome ;)
