### ISSUE TITLE
Possible to change commit message formatting?

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [nicoespeon/gitgraph.js#193]
Hello everyone,
Is there an option to adjust the commit message more freely? 
I have only seen the option to adjust color and font. I would like to print / format the author in bold for example.

Thanks for your help! Have been experimenting with gitgraph for 2 days and love the idea! 
Best regards

**Comment by fabien0102** [comment]
No option like this for now but it's plan for the V2 ;)

**Comment by Gong-Bao-Chicken** [comment]
nice! 😀 Thanks for the info!
