### ISSUE TITLE
Need HELP:: Not able to import GitGraph in my component -gitgraph.d.ts is not a mdule

### ISSUE THREAD

**Issue by Nimzi-Git** [nicoespeon/gitgraph.js#195]
Hi,

This must be a very basic question but need help to configure GitGraph in my project. 
I am trying to import GitGraph module but it is saying that gitgraph.d.ts is not a mdule(**full error::** c:/Projects/Test Projects/firstAngProject/node_modules/gitgraph.js/build/gitgraph.d.ts' is not a module.)
`import GitGraph from '../../../node_modules/gitgraph.js';`
earlier I have just installed using 
npm install --save gitgraph.js
"version": "1.11.4"
Thanks

**Comment by nicoespeon** [comment]
Hi @Nimzi-Git!

I can see the ES6 import syntax here. So, to get more context: how do your project compiles? Are you using babel directly, webpack, parcel? If so, what is the configuration?

If that's any useful, you should find compiled Gitgraph.js files in the `build/` folder.

**Comment by engmagdy87** [comment]
both these importing statements fails
import GitGraph from "gitgraph.js";
import GitGraph from "../node_modules/gitgraph.js/build/gitgraph";

console.log(GitGraph) returns empty object

**Comment by fabien0102** [comment]
Due to the old pattern of gitgraph.js, you need to use this lib like this:

```js
import "gitgraph.js"

console.log(GitGraph)
```

It's a simple function that add `GitGraph` to window ;) (a new version is in progress, with a real integration with ReactJS here -> #188 )

**Comment by engmagdy87** [comment]
@Nimzi-Git 
import "gitgraph.js";
var gitGraph = window.GitGraph;
then replace any **GitGraph** with **gitGraph**
thx @fabien0102 :blush:

**Comment by engmagdy87** [comment]
@fabien0102 
when the new version is expected to be released ?

**Comment by engmagdy87** [comment]
@fabien0102 
I just try to visualize our repo activities and render it using reactjs and may be in future in vuejs

**Comment by fabien0102** [comment]
@engmagdy87 Thanks for your feedback, for now we are focus on the reactjs version (because I prefer react) but all the core logic of gitgraph is now extracted, so it's easier to do a vuejs integration ;)

Just a last question, for your repo activities, it's from github/bitbucket or a custom git repo? (we will working soon on the "import" system, so it's always interesting to have some real usecases to provide the "best" API design as possible 😃 )

**Comment by engmagdy87** [comment]
@fabien0102 from gitlab :grin:

**Comment by engmagdy87** [comment]
@fabien0102 now i just get activities locally using [simple-git](https://www.npmjs.com/package/simple-git) then I will visualize it using gitgraph.js

**Comment by fabien0102** [comment]
For the v2, we will begin with this kind of input -> https://github.com/fabien0102/git2json

A simple lib that extract a pretty json for `git log`, but I will try this `simple-git` it's also look interresting!

**Comment by nicoespeon** [comment]
Thanks @fabien0102 for replying with all the details, you rock 👍 

I'm closing the issue since the initial problem seems solved to me. If it's not the case, please tell me @Nimzi-Git 👌
