### ISSUE TITLE
Display the tip of each branch

### ISSUE THREAD

**Issue by maxime-bus** [nicoespeon/gitgraph.js#199]
Hi,

It would be nice to see where tip branches are, something like this :
                  
           master
             |
             v
    x--x--x--x
       |\
       | x--x--x--x--x
       |      /      ^
        \    /       |
         x--x        |
            ^        |
            |    branch #1
            |
      branch whatever

What do you think :smile: ?

**Comment by nicoespeon** [comment]
Hi @maxime-bus 👋 

Thanks for the suggestion. Indeed, this would be nice. There are other issues that I think are similar to your suggestion: #160 & #142. Would they fit your needs?

Also, regarding current status of this lib: @fabien0102 & I are working on a v2 that would make easier to do such changes. Current modeling makes it challenging to close these issues + there is no test so a high risk of regressions.

You can follow the progression of it with issue #188.

Have a nice day!

**Comment by maxime-bus** [comment]
Hello !

Sorry for the late reply. Indeed, #160 and #142 would fit my needs :). Sorry for the duplicates !
