### ISSUE TITLE
Online playground to generate & export graph

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#203]
I love that [Term Sheets](https://term-sheets.neat.software/) provides an online playground on their website, so you can actually use the tool without installing anything. 👐 

I'd like to do the same on Gitgraph.js website, once v2 is out.

People should be able to:
- export the generated SVG (from `gitgraph-react`)
- export an image

**Comment by rjmunro** [comment]
You can use http://jsfiddle.net/fracz/q76vj8ow/
