### ISSUE TITLE
Problem with declared interface of CommitOptions

### ISSUE THREAD

**Issue by nigtas** [nicoespeon/gitgraph.js#205]
In the example, it is shown, that you can add Id of DOM element, which will be rendered near the commit as details. But the declaration file has CommitOptions interface declared with only detail param, so if using language as Typescript, it is a problem to pass param with Id.
Tried to pass something to detail param, but it is overwritten to null, because in the code detailId is searched...
Seems like a simple bug in declared interface :)

**Comment by nicoespeon** [comment]
Hi @nigtas 👋 

Indeed, I'm not sure how this is interpreted: https://github.com/nicoespeon/gitgraph.js/blob/bf7a58341c8ff418b854fe1cb3e5e7b29b9d3796/src/gitgraph.js#L652-L653

Could you give us the code snippet (or a screenshot) showing the error?

cc @fabien0102 

P.S. : hopefully, this kind of issues will be fixed with #188 since we'll be using proper TypeScript.

**Comment by nigtas** [comment]
Just check up your build folder and file gitgraph.d.ts.
There you will see, what is the interface.

**Comment by fabien0102** [comment]
Everything is generated from the JSDoc here -> https://github.com/nicoespeon/gitgraph.js/blob/develop/src/gitgraph.js#L614

@nigtas If you have any missing props in this interface (or another one), please make a PR and I will review this with pleasure 😉

**Comment by nigtas** [comment]
@fabien0102 Yea, so there is the mistake, detail instead of detailId :) I will check it up later on maybe, if find some time.
Also, I would change default value of message of this George Michael thingy.. Does not look too professional :)
Anyway, little bit offtopic, but.. Is it possible to make this graph kinda zoomed out? I want to make it small and visible with more commits, but spacing does not seem to really help too much with it..

**Comment by nicoespeon** [comment]
So, this is technically _not_ resolved for the `gitgraph.js` package… But we released `@gitgraph/react` in v1.0.0-0 and all types/interfaces are correct there—it's a TS project from the beginning.

Thus, I'm closing this issue as we won't maintain `gitgraph.js` package. There will be a `@gitgraph/js` package soon to replace it. We still accept PRs if someone really needs it though, but I'd suggest moving to the last packages.

Now, I missed to address a few points from your last comments @nigtas:
- For the George Michael thing, well that's a private joke between Fabien & I when we started this side-project. We would like to keep that somehow. Plus, you can override defaults, so it seems fine. Though I thought about it and I see your point. I might create a more neutral default, with an option to go "George Michael" mode for the cheers 🎷 
- There is no simple way to "zoom out" the graph directly, but I guess you could achieve that with CSS on the container. It might be some feature to implement, but I don't have something clear in mind for the moment, so I won't create an issue for now. Feel free to do it if you wish though.

Thanks 👋
