### ISSUE TITLE
Cursor: pointer css on commit element

### ISSUE THREAD

**Issue by AlexCppns** [nicoespeon/gitgraph.js#206]
Hello,

I have been trying to add a cursor: pointer css attribute on my commit elements but I cannot find a way to access them...

**Comment by nicoespeon** [comment]
Hi @AlexCppns 👋 

Indeed, the graph is rendered with canvas, so you can't access commits with CSS to do what you want.

But fortunately, there are events you can plug-in to do this (and they are terribly documented, indeed). For example, a regular ES5 code to change the cursor on commit mouseover would be:

```js
var gitgraph = new GitGraph();

gitgraph.canvas.addEventListener("commit:mouseover", function () {
  this.style.cursor = "pointer";
});

gitgraph.canvas.addEventListener("commit:mouseout", function () {
  this.style.cursor = "default";
});
```

You can find more examples in this file: https://github.com/nicoespeon/gitgraph.js/blob/bf7a58341c8ff418b854fe1cb3e5e7b29b9d3796/examples/index.js#L188-L213

Is it solving your issue?

**Comment by nicoespeon** [comment]
I'm closing the issue since I think it should do what you need. If not, do not hesitate to open it again 👍
