### ISSUE TITLE
When to start gitgraph-angular

### ISSUE THREAD

**Issue by dolanmiu** [nicoespeon/gitgraph.js#208]
Hey,

Don't know if you remember me, but I was interested in creating `gitgraph-angular`. I have a fair amount of Angular experience

Is there a workable `gitgraph` API to use at the moment, or should I wait?

Let me know

Thanks!

**Comment by dolanmiu** [comment]
I am reading `gitgraph-react` now, is `gitgraph-react` really 205 lines long?

It's abit short no?

Can someone give me some usage examples of `gitgraph-react`, so I can create a similar API in `gitgraph-angular`

**Comment by dolanmiu** [comment]
Interesting... There is javascript inside the html. I suppose its this JSX phenomenon I keep hearing about :joy: 

In Angular, the above would be impossible

What can be done is:

```
<gg-graph [config]="config"></gg-graph>
``` 

And in the corresponding `.component.ts` file:

```ts
...

public config: GitGraphConfig;

constructor() {
    const master = gitgraph.branch("master").commit("Initial commit");
    const develop = gitgraph.branch("develop");
    develop.commit("one");
    master.commit("two");
    develop.commit("three");
    master.merge(develop);

    this.config = new GitGraphConfig(master, develop);
}
...
```

I am just brain storming here, what do you guys think? I am open to suggestions

Note: Prefixes like `gg` is common in the Angular world to prevent clash:

https://angular-maps.com/guides/getting-started/ - `agm-` prefix
https://material.angular.io/components/button/overview - `mat-` prefix
https://ng-bootstrap.github.io/#/components/accordion/examples -- `ngb-` prefix

**Comment by fabien0102** [comment]
@dolanmiu I need to update my knowledge in angular (I left after the v2 rc4 ^^). But I want to say that you should give the `gitgraph` instance instead of this gitgraphConfig.

So:

```jsx
<gg-graph [gitgraph]="gitgraph">
```

And 

```ts
...
public gitgraph: GitGraph;

constructor() {
    this.gitgraph = new GitGraph({/* my options */});
    const master = this.gitgraph.branch("master").commit("Initial commit");
    const develop = this.gitgraph.branch("develop");
    develop.commit("one");
    master.commit("two");
    develop.commit("three");
    master.merge(develop);
}
...
```

So you can also manipulate the graph after the first render, as add a commit, and everything should follow. We have this in the react version and it's quite cool, you just need to subscribe to any gitgraph event like this https://github.com/nicoespeon/gitgraph.js/blob/2.0.0/packages/gitgraph-react/src/Gitgraph.tsx#L34 :wink:

**Comment by dolanmiu** [comment]
I will consider this, a potential problem I can see with mutating the `GitGraph` object is that it may not kick off change detection, but who knows

**Comment by dolanmiu** [comment]
![image](https://user-images.githubusercontent.com/2917613/47535288-afcc9a00-d8b2-11e8-96ba-768c8cfb298b.png)

I am getting this error when creating `gitgraph-angular`

Any ideas?

**Comment by dolanmiu** [comment]
Huge progress on the Angular side 😄 
![image](https://user-images.githubusercontent.com/2917613/47538088-73546a80-d8c1-11e8-8dad-ae43f629cb67.png)

**Comment by fabien0102** [comment]
@dolanmiu Strange for the circular dependency, are you up to date with `2.0.0`? (I remember an issue like this, but it should be fixed (if it's the same issue))

**Comment by nicoespeon** [comment]
@dolanmiu I'm closing this issue as the discussion might hold all along the development of gitgraph-angular.

I suggest we move that discussion into another, more dynamic channel. Fabien & I are mostly discussing on Discord. If you're interested in participating, I could create a server. Just let me know if you're in 👍
