### ISSUE TITLE
Documentation of v2

### ISSUE THREAD

**Issue by dolanmiu** [nicoespeon/gitgraph.js#213]
Have you considered doing documentation with docsify? https://docsify.js.org/#/quickstart

And free js.org domain? https://js.org/

Example of what I did before: https://docx.js.org/#/

https://github.com/dolanmiu/docx/tree/master/docs

**Comment by nicoespeon** [comment]
Thanks for sharing @dolanmiu, it looks interesting indeed.

We'll need to talk about documentation of v2. There is the core lib, and all of the independent rendering libs… 

I'd say each rendering lib should deal with its own documentation for end-user. So it'd be up to them to choose whatever solution they want (e.g. the React one might use something like [styleguidist](https://react-styleguidist.js.org/docs/getting-started.html)). 

Core lib could provide a documentation too, for rendering libs maintainers.

Is there any pros of docsify over gitbook?

**Comment by dolanmiu** [comment]
I have not used gitbook, but docsify is hosted on github pages, and all documentation can be stored in a `/docs` directory of the repository, which is more centralized

From reading gitbook, it seems you need to sign up to another service

**Comment by nicoespeon** [comment]
Good to know, thanks!

**Comment by nicoespeon** [comment]
Closing this in favor of #36. Ported the suggestion there. Thanks =)
