### ISSUE TITLE
Update GitHub Pages

### ISSUE THREAD

**Issue by cardil** [nicoespeon/gitgraph.js#217]
GitHub pages are not up to date.

GitFlow example is not current, for example.

**Comment by nicoespeon** [comment]
Hi @cardil 👋 

Indeed, the website might not be up-to-date. It may not describe all features of the lib. The truth is we didn't updated the website through releases.

As we're working on v2, we planned to revamp the online website though:
- https://github.com/nicoespeon/gitgraph.js/issues/203 for having an online playground 
- https://github.com/nicoespeon/gitgraph.js/issues/213 for documenting the API

Though, I'm not sure I get what you mean with "GitFlow example is not current"?

**Comment by cardil** [comment]
Here:
![image](https://user-images.githubusercontent.com/540893/51922793-0a155380-23ea-11e9-8253-49033bd601d8.png)

**Comment by nicoespeon** [comment]
I just updated the website examples, as well as the version of gitgraph that was used in the examples.

As for the main page, I think content is still relevant. v2 will have a more exhaustive user documentation while v1 mostly exposed examples to go further.

Closing the issue, but feel free to tell me if you spot something outdated in particular.
Again, thank you!
