### ISSUE TITLE
gitgraph-react sample code does not work

### ISSUE THREAD

**Issue by FeynmanDNA** [nicoespeon/gitgraph.js#229]
**Describe the bug**
![image](https://user-images.githubusercontent.com/26617036/52941137-17977b00-33a3-11e9-9153-45d2d318d918.png)

The `const { Gitgraph } = require("@gitgraph/react");` line causes the react to fail to compile with the following error message:
```
Module not found: Can't resolve '@gitgraph/react'
```

**To Reproduce**

Go to https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-react

**Desktop (please complete the following information):**

- OS: Debian
- Browser Vivaldi
- Version `"gitgraph-react": "^2.0.0-alpha.73bd2e56"`

**Comment by gabor-udvari** [comment]
The version `2.0.0-alpha.73bd2e56` does not seem to be [scoped](https://docs.npmjs.com/misc/scope), so you have to require/import it as `gitgraph-react` instead of `@gitgraph/react`.

**Comment by FeynmanDNA** [comment]
@gabor-udvari thanks for your reply and help! 

I actually tried to import with `gitgraph-react`, but when i do that react-webpack wont even compile:
![image](https://user-images.githubusercontent.com/26617036/52997676-2db54200-345c-11e9-853b-1e61097a624d.png)

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

**Comment by nicoespeon** [comment]
Hi @FeynmanDNA 👋 

I actually missed this issue. Thanks to your feedback, I realized installation instructions were outdated: this is `@gitgraph/react` that should be installed, not `gitgraph-react`. I fixed them.

I also noticed that [`gitgraph-react`](https://www.npmjs.com/package/gitgraph-react) does exist as we did try a canary release 4 months ago. @fabien0102 do you know if we can remove it from npm easily?

@FeynmanDNA as per [your last comment on the other issue](https://github.com/nicoespeon/gitgraph.js/issues/187#issuecomment-467711270), is this one still relevant? Or did you managed to get it work?

**Comment by fabien0102** [comment]
Maybe not easily but you should be able to do something 😉

**Comment by FeynmanDNA** [comment]
@nicoespeon i ended up still using `"gitgraph.js": "^1.15.1"` in my react project, following the discussion from this thread:
https://github.com/nicoespeon/gitgraph.js/issues/195

:)

**Comment by nicoespeon** [comment]
Good to know. I'm closing the issue since the gitgraph-react sample code was fixed. Everything should work now.
