### ISSUE TITLE
Display tags in horizontal mode

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#237]
Tags are currently not rendered in horizontal mode. It could be a nice info to have though.

![image](https://user-images.githubusercontent.com/1094774/54731778-93cddb80-4b66-11e9-8a6a-ceca95ddf9ea.png)

But I'm not quite sure what it should look like. Horizontal mode is challenging. 

I'm open to suggestions on this one 👐

**Comment by nicoespeon** [comment]
I'm thinking about that kind of rendering (as suggested in #173):

![image](https://user-images.githubusercontent.com/1094774/54731891-2ec6b580-4b67-11e9-9dc2-ad734f271f10.png)

![image](https://user-images.githubusercontent.com/1094774/54731893-31290f80-4b67-11e9-8d6b-ce286b06e1d0.png)

But that might imply to change how branch labels are rendered.

**Comment by thomasfourest** [comment]
I like it. 
it will be a great "must-have" !

**Comment by parthiban-powerschool** [comment]
Is "displaying tags for horizontal orientation" implemented yet?
