### ISSUE TITLE
How to render the graph automatically?

### ISSUE THREAD

**Issue by JulienLamy76** [nicoespeon/gitgraph.js#238]
Hi,

I would like to render automatically the graph in javascript (best graph I've seen so far and I need it for javascript).
I would like to know if there are good news for the rendering like the "import" way on react but this time, in javascript.

For the moment, I can generate commit array from two libraries that I'm using
(which are https://isomorphic-git.org/ and https://github.com/types/simple-git)
(Because I would like to generate the render of the command git log --all --graph --date-order --oneline)
I also saw the git2json solution.

My problem is :
How can I render the graph automatically from my arrays with the "import" way.
Or : How can I use the git2json or similar thing to have a json object in my code then render the graph from it.
(If someone ever needed to do this, it would make a lot of sense for me)

Thank you for your answers!

**Comment by nicoespeon** [comment]
Hi @JulienLamy76 👋 

The `import` feature is still a bit experimental, so I'm not 100% sure it will generate your graph without issue—especially if it's a big one. But I'd be really happy to get your feedbacks so we can improve it until it works. Or maybe it will just work fine for you and you'll be good to go!

Anyway, you'll indeed need to generate a JSON output using [@fabien0102's git2json](https://github.com/fabien0102/git2json). To do so, you need to have the git project locally. Then just follow the instruction in git2json README (here's a screenshot of what you need):

![image](https://user-images.githubusercontent.com/1094774/54870188-89376000-4d79-11e9-9751-6063281c9e8e.png)

Now, for the rendering part, there is no `@gitgraph/js` (vanilla JS rendering lib) available yet, only the `@gitgraph/react` one. But, I'm currently working on it: #219. It's literally my next step, so I should have something available for you in the following 2-3 weeks, I'd say.

**Comment by JulienLamy76** [comment]
Hi,

I take advantage of having an issue to ask an additional question.
For now, I'm using the canvas with gitgraph.js.

I would like as already said to have a graph similar to the command `git log --all --graph --date-order --oneline`
For now, I know how to create branches and commits from them.
However, how can I tell that a commit can have multiple branches, for example:
develop, origin / develop and first-feature?

In addition, is there anything special to do also when develop and origin/develop must be on the same column?

To support my comments here is this screenshot that I could observe somewhere:
![image](https://user-images.githubusercontent.com/37408467/55277148-4dfadb00-52fd-11e9-933d-db3823889466.png)

(It could help me a lot knowing that I can recover an object from commits in different ways. A commit object with the parent commit or also a commit object with all associated branches for each commit.)

-> With the command git log --all --graph --date-order --oneline I can get this :
```
* 8896805 (origin/firstbranch) test(firstbranch): this is my commit on this branch
| * 5fef2da (HEAD -> testbranch, origin/another, another) refactor(another): this is a change
| * 2a34d72 refactor(another): typo
| * 683d704 refactor(another): changes
* |   0120274 Merge remote-tracking branch 'origin/develop' into firstbranch
|\ \
```

and with that get an object of this type:
```
[
  {
    "commitHash": "8896805",
    "branches": [
      "origin/firstbranch"
    ],
    "commit": "test(firstbranch): this is my commit on this branch"
  },
  {
    "commitHash": "5fef2da",
    "branches": [
      "testbranch",
      "origin/another",
      "another"
    ],
    "commit": "refactor(another): this is a change"
  },
  {
    "commitHash": "2a34d72",
    "branches": [],
    "commit": "refactor(another): typo"
  },
  {
    "commitHash": "683d704",
    "branches": [],
    "commit": "refactor(another): changes"
  },
  {
    "commitHash": "0120274",
    "branches": [],
    "commit": "Merge remote-tracking branch 'origin/develop' into firstbranch"
  },
  {
    "commitHash": "",
    "branches": [],
    "commit": ""
  }
]
```

Which here would be a good example to illustrate the case of several branches on a commit.

Sorry for the inconvenience and thank you again for your responsiveness and your project!

**Comment by nicoespeon** [comment]
Hi again @JulienLamy76 👋 

> However, how can I tell that a commit can have multiple branches, for example: develop, origin / develop and first-feature?

It's a very good question and I actually realized it's not possible today. Someone else open an issue to do exactly that, so we'll implement it: #258 

Also, regarding your first question, `@gitgraph/js` is available so you can give it a look and try Gitgraph without having to use the React version.

Let me know if that solves your questions ;-)

**Comment by nicoespeon** [comment]
Closing the issue since the question has been answered. #258 will track discussion for mentioned feature.
