### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by canhbd** [nicoespeon/gitgraph.js#240]
Hello and thanks for great this lib.

Please share me this source code,

![image](https://user-images.githubusercontent.com/45847757/54837121-35386700-4cf8-11e9-9e40-70cfa0ac54d6.png)
https://github.com/nicoespeon/gitgraph.js/pull/216
Thanks you!

**Comment by nicoespeon** [comment]
Hi @canhbd 👋 

It's a variant of the following example of [`gitgraph.js` (v1)](https://www.npmjs.com/package/gitgraph.js): http://gitgraphjs.com/examples/gitflowsupport.html

It's the same code, but without forcing the colors of the branches and commit dots. Thus, you can use the following template config:

```js
var customTemplate = new GitGraph.Template({
  colors: [ "#9993FF", "#47E8D4", "#6BDB52", "#F85BB5", "#FFA657", "#F85BB5" ],
  branch: {
    lineWidth: 3,
    spacingX: 60,
    mergeStyle: "straight",
    showLabel: true, // display branch names on graph
    labelFont: "normal 10pt Arial",
    labelRotation: 0
  },
  commit: {
    spacingY: -30,
    dot: {
      size: 8,
      strokeWidth: 4
    },
    tag: {
      font: "normal 10pt Arial",
      color: "yellow"
    },
    message: {
      color: "black",
      font: "normal 12pt Arial",
      displayAuthor: false,
      displayBranch: false,
      displayHash: false,
    }
  },
  arrow: {
    size: 8,
    offset: 3
  }
});

var gitgraph = new GitGraph({
  template: customTemplate,
  mode: "extended",
  orientation: "horizontal"
});
```

I'm closing the issue, but let me know if you have any issue in making this work!
