### ISSUE TITLE
Move react as a peer dependency

### ISSUE THREAD

**Issue by ohjimijimijimi** [nicoespeon/gitgraph.js#245]
**Describe the bug**
React should not be included as a dependency

**To Reproduce**
Check this sandbox: https://codesandbox.io/embed/183o7kx59q

**Expected behavior**
Users should be able to add React and not be forced to use the one in the package.

**Screenshots**
![image](https://user-images.githubusercontent.com/766504/55078128-b5185580-5099-11e9-9714-d0694d6c773d.png)

**Additional context**
The error happens because the library is pulling React version 16.8.4 and I'm using another version.

**Comment by nicoespeon** [comment]
Oh, good catch 👍 

Indeed, we'll clean that up.

**Comment by nicoespeon** [comment]
Hello @ohjimijimijimi 👋 

Thanks again for reporting. This have been fixed and published under `@gitgraph/react@1.1.0-3`. 
You can see it working: https://codesandbox.io/embed/q95y6ypjrw
