### ISSUE TITLE
Is it possible to set offset for first element, if it is on the bottom?

### ISSUE THREAD

**Issue by alvassin** [nicoespeon/gitgraph.js#249]
![problem](https://user-images.githubusercontent.com/1497444/55231098-b0d37000-5232-11e9-859f-8027ebea1e58.png)

As you can see root element is half-cropped. How can i add some offset for it from the bottom?

P.S. here is my template:
```
const myTemplate = new GitGraph.Template({
        mode: 'compact',
        colors: ["#979797", "#008fb5", "#f1c109"],
        tooltipDisplay: true,
        branch: {
          showLabel: true,
        },
        commit: {
          dot: { size: 4 },
          message: {display: false}
        },
      })
```

**Comment by nicoespeon** [comment]
Hi @alvassin 👋 

This seems to be the `gitgraph.js` package, right? If so, I think the simplest solution would be to add some padding to the `canvas#gitGraph` element using CSS. Can you try that and let me know if it works?

Now, there will soon be a `@gitgraph/js` package (see #219) to replace `gitgraph.js`. A bunch of fixes (including properly calculating the dimensions of the graph) will be baked in. I'd recommend to give it a try when it's ready. 

There also is a `@gitgraph/react` almost ready, if you're into React.

**Comment by alvassin** [comment]
Thank you for response!  Yes, I am using gitgraph.js package.

I found `initCommitOffsetY` and `initCommitOffsetX`options, but they did not work for me, because i specified them in GitGraph.Template instead of passing them directly to the GitGraph constructor.

So, when i specified them like in example below, it worked like a charm. 

```
const graph = new GitGraph({
	template: new GitGraphTemplate({
		... template options ...
	}),
	initCommitOffsetY: -20,
})
```
