### ISSUE TITLE
Merge and commit renders incorrectly on vertical-reverse

### ISSUE THREAD

**Issue by kennyeni** [nicoespeon/gitgraph.js#251]
**Describe the bug**
When a merge is done from branch A to branch B, and then a commit is done on branch A the rendering is incorrect.

**To Reproduce**
a.commit();
b.merge(a)
a.commit();

**Expected behavior**
Vertical-reverse rendering should work as vertical rendering

**Screenshots**
Vertical rendering (correct):
![image](https://user-images.githubusercontent.com/972669/55266571-f09e5580-523a-11e9-83a6-f52748ae21f4.png)

Vertical-reverse rendering (incorrect):
![image](https://user-images.githubusercontent.com/972669/55266598-0ca1f700-523b-11e9-9e0c-6037c9b7cc47.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser: Chrome
- Version: latest

**Comment by nicoespeon** [comment]
Thanks for reporting @kennyeni 👋 

We'll have a look and fix this =)

**Comment by nicoespeon** [comment]
@kennyeni thanks for reporting! This has been fixed and published under `@gitgrap/react` v1.1.0-4 👍
