### ISSUE TITLE
One commit can't serve as a parent to multiple merge commits (> 2)

### ISSUE THREAD

**Issue by briangordon** [nicoespeon/gitgraph.js#259]
This example is very close to what I would like to diagram-

```
      {(gitgraph) => {
        const develop = gitgraph.branch("develop").commit();
        const fix = gitgraph.branch("feature");
        const release = gitgraph.branch("release");
        fix.commit("Bug fixed.");
        release.merge(fix);
        develop.merge(release, "Bugfixes are always merged back to develop.");
      }}
```

<img width="243" alt="screenshot-1" src="https://user-images.githubusercontent.com/1331024/55691403-bcb9e300-5952-11e9-84de-9bef68bb5366.png">

However, with a little bit of mspaint-

<img width="243" alt="screenshot-1" src="https://user-images.githubusercontent.com/1331024/55691454-19b59900-5953-11e9-8271-537478f8b55e.png">

This seems to be impossible to build in gitgraph. I would expect the following code to work, but it breaks horribly.

```
      {(gitgraph) => {
        const develop = gitgraph.branch("develop").commit();
        const fix = gitgraph.branch("feature");
        const release = gitgraph.branch("release");
        fix.commit("Bug fixed.");
        release.merge(fix);
        develop.merge(fix, "Bugfixes are always merged back to develop.");
      }}
```

**Comment by nicoespeon** [comment]
Hey @briangordon 👋 

What package/version of gitgraph are you using currently?

I added a story to illustrate the behavior, and it seems to work as expected with the last version of `@gitgraph/react` and `@gitgraph/js`:

![image](https://user-images.githubusercontent.com/1094774/55954004-8965a580-5c2b-11e9-93f2-59f8c9c5198e.png)

```jsx
  .add("multiple merges from same commit", () => (
    <Gitgraph options={{ generateCommitHash: createFixedHashGenerator() }}>
      {(gitgraph) => {
        const master = gitgraph.branch("master");
        master.commit("Initial version");

        const develop = gitgraph.branch("develop").commit("Do something");
        const fix = gitgraph.branch("fix");
        const release = gitgraph.branch("release");
        fix.commit("Bug fixed.");

        release.merge(fix);
        develop.merge(fix, "Bugfixes are always merged back to develop");

        master.merge(develop, "New release");
      }}
    </Gitgraph>
  ))
```

**Comment by briangordon** [comment]
Aha, indeed this has been fixed in the couple of weeks since I forked the repository. Sorry about that!

I also just realized that I've been using the reverse orientation in all of my bug reports inadvertently, since that's what I've been using for my work. Sorry about that too; I guess it's probably unnecessarily confusing. 😅

**Comment by nicoespeon** [comment]
@briangordon Ah ah, don't worry, I figured out the orientation quickly 😉 

I hope the latest version will help you to achieve what you want 👍

**Comment by briangordon** [comment]
@nicoespeon Actually, it seems like this issue might not be completely resolved. The case of two child merges does indeed work, but the case of _three_ child merges does not. 

Here's the 2 case working fine:

<img width="145" alt="screenshot" src="https://user-images.githubusercontent.com/1331024/56235079-83acfd00-603b-11e9-89b8-da07d7ca5569.png">

```
      {(gitgraph) => {
        const develop = gitgraph.branch("develop").commit();
        const fix = gitgraph.branch("feature1");
        const release1 = gitgraph.branch("release1");
        fix.commit();
        release1.merge(fix);
        develop.merge(fix);
      }}
```

And here's the 3 case looking slightly off:

<img width="196" alt="screenshot-1" src="https://user-images.githubusercontent.com/1331024/56235101-945d7300-603b-11e9-9048-dac368c23d4f.png">

```
      {(gitgraph) => {
        const develop = gitgraph.branch("develop").commit();
        const fix = gitgraph.branch("feature1");
        const release1 = gitgraph.branch("release1");
        const release2 = gitgraph.branch("release2");
        fix.commit();
        release1.merge(fix);
        release2.merge(fix);
        develop.merge(fix);
      }}
```

Notice that in the 3 case, the green-to-grey merge is rendered as coming from the orange merge commit for some reason.

**Comment by nicoespeon** [comment]
Indeed, that's interesting. Thanks for adding more details, we'll look into this 👍
