### ISSUE TITLE
Custom renderers for branch labels & tags

### ISSUE THREAD

**Issue by Andrey-Pavlov** [nicoespeon/gitgraph.js#262]
**Is your feature request related to a problem? Please describe.**
Can't style or format labels as I want

**Describe the solution you'd like**
I want to use custom markup for labels (HTMLFormatter?)

**Describe alternatives you've considered**
Allow to use rendering process hooks

**Additional context**
This was my custom method to render labels in V1:

```
  GitGraph.prototype.drawAllLabels = function (verticalOffset) {
    this.verticalOffset = verticalOffset;
    this.commits.forEach((commit) => {
      let element = document.getElementById(commit.sha1);
      if (!element) {
        if (commit.tag || commit.branches) {
          element = document.createElement('div');
          element.classList.add('git-graph-label');
          element.id = commit.sha1;

          if (commit.tag) {
            element.insertAdjacentHTML('beforeend', `<i class="fas fa-tag" aria-hidden="true"></i>&nbsp;${commit.tag}`);
          }

          if (commit.branches) {
            element.insertAdjacentHTML('beforeend', `<i class="fas fa-code-branch" aria-hidden="true"></i>&nbsp;${commit.branches}`);
          }

          element.style.display = "block";

          this.canvas.parentElement.parentElement.appendChild(element);
        }
      }

        if (element) {
          var distanceX = (commit.x + (this.offsetX + this.marginX) / this.scalingFactor);
          var distanceY = (commit.y + (this.offsetY + this.marginY) / this.scalingFactor);

          element.style.left = distanceX + 5 + "px";
          element.style.top = distanceY - 33 + verticalOffset + "px";
        }
      }
    );
  };
```

**Comment by nicoespeon** [comment]
By "label" I assume you're referring to both branch labels & tags.

Indeed, these can be styled a bit, but you can't provide a custom renderer as you could have done in v1. 

I think we can create 2 custom methods to render branch label & tags. We do the same with tooltips, commit messages and commit dots actually: https://github.com/nicoespeon/gitgraph.js/blob/cda0b6db3892ea6588681b7ad0868f886390a18b/packages/gitgraph-core/src/commit.ts#L8-L12

I'll note this as a feature to be re-implemented in v2. Thanks for spotting 👍
