### ISSUE TITLE
Multi-head graphs

### ISSUE THREAD

**Issue by SumNeuron** [nicoespeon/gitgraph.js#267]
I like your library as a concept as it is basically tree / hierarchical graph drawing. The js libraries that support this well are few and far between! (your's looks nice though)

Would be nice for multi-headed graphs (not necessarily a git graph...) 

You might be thinking we specialize on git related graphs. This is not git related.

Then please think of this feature request as letting the user start in the midway of the git history.

e.g. there are 10 branchs and 2000 commits. 

I want to render a stage of the project where there are only 3 branchs and 10 commits and then paginate over the next 10, etc.

i.e. multi-headed graph is a graph with a single head, where the head and its immediate edges are hidden

**Comment by nicoespeon** [comment]
Hi @SumNeuron and thanks for the kind words!

If I correctly understand, this sounds like a partial rendering of the graph, with the possibility to navigate in history, still displaying a subset of the whole graph.

If that's what is proposed here, there's an discussion around that tracked in this issue: https://github.com/nicoespeon/gitgraph.js/issues/215

I suggest you give it a look and I encourage you to add your opinion in this other issue, with usage example of how you'd like to achieve this. In particular, I wonder if my last comment wouldn't help you to do this already:

> I kinda implemented something similar in the `gitgraph-node` package. There's a `bufferGraphLogger` that only renders part of the graph—needed because height of the terminal might be smaller than the graph. Implementation is mostly a `graphRenderedData.slice(start, end)`. So it might already be doable in rendering libraries.

I'm closing this issue so we keep the conversation at a single place. But don't hesitate to tell me if your proposition is different, I might have misunderstood it.

Thanks 👍
