### ISSUE TITLE
Create branch at specific commit

### ISSUE THREAD

**Issue by JackWilliam277** [nicoespeon/gitgraph.js#270]
Hi,

I'm using the latest version of @gitgraph/js.

For the moment, the `import()` is a bit experimental so I'm creating the graph manually with my objects.

The problem is that 

```ts
    const master = gitgraph.branch('master');
    master.commit({hash:'0001', subject: 'first'});
    master.commit({hash:'0002', subject: 'second'});
    const develop = gitgraph.branch('develop'); 
    develop.commit({hash:'0003', subject: 'third'}); 
    master.commit({hash:'0004', subject: 'fourth'});
    develop.commit({hash:'0005', subject: 'another'});
    master.commit({hash:'0006', subject: 'another one'});
```

But if I want to create a new branch from the commit with the hash '0004' after the last commit, I can't specify the parentCommit from which I need to create the branch.

With the actual version, I'm forced to create the branch just after the commit that I want, but the problem is that I'm doing a loop on my object and need to create a branch at a specific commit when needed.

Is there a way to do it?

**Comment by nicoespeon** [comment]
Hi @JackWilliam277 👋 

That's an excellent question and there is actually an old issue to implement this feature: https://github.com/nicoespeon/gitgraph.js/issues/162

I liked your title though, it's more explicit. I'm closing this one to focus the discussion on one single issue, and I'll rename it after this one.

👍
