### ISSUE TITLE
Create branch from another one

### ISSUE THREAD

**Issue by JackWilliam277** [nicoespeon/gitgraph.js#271]
Hi,

I'm now using @gitgraph/js (v2 instead of the v1).
The problem is that even with the migration help page between v1 and v2 (https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/MIGRATE_FROM_GITGRAPH.JS.md)
I don't know since the v2 how to create a branch from another one.

There is a way to do it? Thanks!

**Comment by nicoespeon** [comment]
Hi @JackWilliam277 !

Currently, the only way to create branch is with `gitgraph.branch()`. That means you can only create a branch at a specific moment in time, and it will take current HEAD as the parent commit of the branch.

This is very related to the fact you can't create a branch at a specific commit: https://github.com/nicoespeon/gitgraph.js/issues/162

I'll keep this issue open as a feature to implement. Thanks for the suggestion 👍
