### ISSUE TITLE
Render the website as a single-page by default

### ISSUE THREAD

**Issue by Andrey-Pavlov** [nicoespeon/gitgraph.js#275]
Hi,

Don't know where to share my feedback so I leave it here.
I don't like the new website design and think the older version is much cleaner and more readable.
Previously, you got all information in one place. With a simple scrollable page it much easier to see and understand connected parts in opposite to wizard layout with pagination.

Thank you.

**Comment by nicoespeon** [comment]
Thanks for the feedback @Andrey-Pavlov 👍 

Indeed, I wasn't quite sure of the end result from an end-user point of view. I added more context to explain why I went for this design: https://github.com/nicoespeon/gitgraph.js/pull/272

Although, I anticipated this option:

> If it turns out to be annoying, we would probable be able to generate a "single-page website" version from the content.

I'll keep the issue open as you probably are not the only one. I'll see if I could get it to render on a single page by default.

**Comment by nicoespeon** [comment]
I also think it would address #278 to change the way information is organized.

For the moment, it's:
1. Installation JS & React
1. Set-up JS & React
1. Basic usage
1. Resulting graph

I think it would be less confusing if it was organized by stack, from A to Z:
1. Installation & set-up JS
1. Example of basic usage JS with resulting graph
1. Installation & set-up React
1. Example of basic usage React with resulting graph
1. More basic usage examples, now that people understand the core is the same

**Comment by nicoespeon** [comment]
Also to consider:

- [ ] Add "see source code" links to examples
- [ ] Use a toggle component to switch between JS / React instructions (so previous instructions would be simpler to follow)
