### ISSUE TITLE
Gitgraph import JSON merges branches to the right

### ISSUE THREAD

**Issue by Andrey-Pavlov** [nicoespeon/gitgraph.js#276]
**Describe the bug**
GitGraph Import JSON doesn't render dag correctly as any GIT visualizer. It merge branches to the right side.

**To Reproduce**
Get any complicated git repository, for example, "gitgraph.js". Generate JSON with GitToJson npm module.
```
    const graphContainer = this.gitGraphCanvas.nativeElement;
    const gitGraph = createGitgraph(graphContainer);
    gitGraph.import(commits);
```

**Expected behavior**
"Master" branch must stay on the left / not growing to the right.
Repo with screenshots: [ScreensRepo](https://github.com/Andrey-Pavlov/GitGraphJSProblems)

**Screenshots**
![MergeRight1](https://github.com/Andrey-Pavlov/GitGraphJSProblems/blob/master/4.15.2019/MasterSlave.png?raw=true)
![MergeRight2](https://github.com/Andrey-Pavlov/GitGraphJSProblems/blob/master/4.15.2019/MergeRight.png?raw=true)
<details><summary>Full GitGraphJs dag</summary>
<p>

![My1](https://github.com/Andrey-Pavlov/GitGraphJSProblems/blob/master/4.15.2019/GitGraphJSON.jpg?raw=true)
</details>

My repo:
<details><summary>More Screens</summary>
<p>

![My1](https://github.com/Andrey-Pavlov/GitGraphJSProblems/blob/master/4.15.2019/MyRepo1.png?raw=true)
![My2](https://github.com/Andrey-Pavlov/GitGraphJSProblems/blob/master/4.15.2019/MyRepo2.png?raw=true)
</details>

**Comment by IsaacHub** [comment]
I couldn't find `GitToJson` in npm, there is no such package. Can you post a link to the npm module.

**Comment by Andrey-Pavlov** [comment]
@IsaacHub In this issue (https://github.com/nicoespeon/gitgraph.js/issues/38) was mentioned: https://github.com/fabien0102/git2json (https://github.com/nicoespeon/gitgraph.js/issues/38#issuecomment-462098910)

I also used it to render GIT dag from JSON

**Comment by JUSTDIWAKAR** [comment]
Hi @Andrey-Pavlov,

It's been too late but to anyone else facing the same problem, you can fix ur problem by applying some CSS to rotate that gitgraph element.
like,
  ::ng-deep svg {
    transform: scaleX(-1) rotate(90deg);
  }
