### ISSUE TITLE
Gitgraph import JSON doesn't work with partial data

### ISSUE THREAD

**Issue by Andrey-Pavlov** [nicoespeon/gitgraph.js#277]
**Describe the bug**
If you have commits filtered by date range you can't render Git graph. The same if you have missed parent nodes.

**To Reproduce**
Remove any commit with id from any parentIds array.

**Expected behavior**
Expect to have "open" starts and ends.

**Screenshots**
I expect:
![My1](https://github.com/Andrey-Pavlov/GitGraphJSProblems/blob/master/4.15.2019/PartialData.png?raw=true)

**Additional context**
In my project (kinda CD/CI tool) I have the functionality to show delta commits between TeamCity builds. I want to show Git dag for this delta commits.

**Comment by Symbolk** [comment]
Same problem for me, when I want to just show the latest N commits from git2json.

**Comment by Symbolk** [comment]
@Andrey-Pavlov A workaround is to manually set the parents of the last commit to empty, to make the gitgraph renderable.

For example, display at most 20 commits:
```javascript
      git2json.run().then(gitlog => {
        // display at most 20 commits for performance
        if (gitlog.length <= 20) {
          this.gitGraph.import(gitlog)
        } else {
          let slicedLog = gitlog.slice(0, 20)
          slicedLog[slicedLog.length - 1].parents = []
          this.gitGraph.import(slicedLog)
        }
      })
```
@nicoespeon Do you have any better idea?

**Comment by nicoespeon** [comment]
@Symbolk I don't, I think it's the simplest way to "cut" the graph today indeed 👍

**Comment by Symbolk** [comment]
> @Symbolk I don't, I think it's the simplest way to "cut" the graph today indeed 👍

However, this workaround sometimes leads to an error:

![image](https://user-images.githubusercontent.com/14107297/63266004-89547100-c2c1-11e9-9f15-ef699b38260c.png)
