### ISSUE TITLE
Orientation.VerticalReverse renders incorrectly

### ISSUE THREAD

**Issue by briangordon** [nicoespeon/gitgraph.js#282]
In the reverse vertical orientation, the dark blue release branch lies over the develop branch in the following screenshot:

<img width="256" alt="screenshot" src="https://user-images.githubusercontent.com/1331024/56234071-55c6b900-6039-11e9-9a81-ffe92e28f409.png">

However, in the standard orientation, the dark blue release branch is correctly routed so that it doesn't overlap the develop branch:

<img width="251" alt="screenshot-1" src="https://user-images.githubusercontent.com/1331024/56234082-5a8b6d00-6039-11e9-853f-e9447cc75385.png">

This is the code I'm using:

```typescript
      {(gitgraph) => {
        const develop = gitgraph.branch("develop").commit();
        const feature1 = gitgraph.branch("feature1").commit();
        develop.merge(feature1);
        const fix = gitgraph.branch("feature3");
        const release = gitgraph.branch("release1");
        const feature2 = gitgraph.branch("feature2");
        feature2.commit();
        develop.merge(feature2);
        fix.commit();
        release.merge(fix);
        develop.merge(fix);
      }}
```

**Comment by nicoespeon** [comment]
Thanks for the detailed feedback, we'll look into it 👍

**Comment by lhassis** [comment]
Hi everyone! I have the same issue! Do we have any news on this?
In my example:
reversed
![image](https://user-images.githubusercontent.com/49009472/100618299-6903c680-32fa-11eb-8f17-1bf5bcdb8e48.png)
natural
![image](https://user-images.githubusercontent.com/49009472/100618343-7de05a00-32fa-11eb-95c5-4ee29ba3a4c8.png)

Just to add more detail, I saw that if we add a new commit or a merge after the last one on the new branch, the graph draws correctly even on the vertical-reversed orientation. The below example shows that.
![image](https://user-images.githubusercontent.com/49009472/100618535-b97b2400-32fa-11eb-90ec-3495b33ede4b.png)

**Comment by lhassis** [comment]
Hi everyone!
I managed to solve the problem on my example by changing the first `if` on the `smoothBranchesPaths `function to check if `length `is less or equal than 2. The result is show in the image below
![image](https://user-images.githubusercontent.com/49009472/100752393-50151700-33c7-11eb-9540-8933a7dbbf01.png)

So far, it was enough to my application but I'm no sure if this the deffinitive solution, since I don't know the component code details well enough.

**Comment by gsGupta11** [comment]
Is this problem solved?

**Comment by gsGupta11** [comment]
> Thanks for the detailed feedback, we'll look into it 👍

Any solution to this problem?

**Comment by nicoespeon** [comment]
Not that I'm aware of 🙂 

To be clear: I'm not working/maintaining this lib anymore. The issue is still open to be solved with the provided details.
