### ISSUE TITLE
Make it possible to use `@gitgraph/js` without NPM (CDN)

### ISSUE THREAD

**Issue by enlait** [nicoespeon/gitgraph.js#283]
v1 has plenty of examples on how to just include js and css from CDN and get hacking.

Can't find any info on this for v2 and wasn't able to get it working yet.

No I'm not using NPM.

**Comment by nicoespeon** [comment]
`@gitgraph/js` is not available on a CDN yet, indeed. This is something we should consider so people don't have to use NPM 👍 

Until then, you can still use v1. I put the documentation back online at https://gitgraphjs.com/v1

**Comment by nicoespeon** [comment]
Reference on how we get v1 on CDN.js => https://github.com/cdnjs/cdnjs/issues/7642

**Comment by nicoespeon** [comment]
I think we need to publish the `bundle.umd.js` (generated in gitgraph-js' `lib/`) somewhere, so people can download it / inject it in their webpage and then start coding.

Ideally, we should also provide a minified version of it—I noticed it's not.

**Comment by parmentelat** [comment]
+1; having the ability to start playing around with v2 right away from a cdn would be much appreciated 

thanks for the cool tool :)

**Comment by parmentelat** [comment]
@nicoespeon: following up on this mention:

> I think we need to publish the bundle.umd.js (generated in gitgraph-js' lib/) somewhere, so people can download it / inject it in their webpage and then start coding.

where can I find the doc that explains how to build this `bundle.umd.js` file from a cloned git repo ?
first off I need to stress that I am no javascript guru:) so, I've kinda tried to guess, with `npm run build` but that pulled further requirements wrt lerna, and yarn, that I tried to `npm install as well`, but it's now failing with

```
lerna info Executing command in 3 packages: "yarn run build"
@gitgraph/core: yarn run v1.15.2
@gitgraph/core: $ run-s build:*
@gitgraph/core: /bin/sh: run-s: command not found
```

so I guess it's best to back off and use your instructions, that will benefit others as well in the process :)

thanks !

**Comment by parmentelat** [comment]
I've given this one last push; 
I've also tried one recipe that I've found here:
https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js

and that was about using
npm i --save @gitgraph/js

but the instructions in the 'Get started' sections don't seem to work for me:

* I did create the simple html file, embedded the sample javascript code
* tried to open that page in chrome
* javascript error'ed saying that require is undefined
* inserted `require.js` from cdnjs
* and ended up with this message:

    Uncaught Error: Module name "@gitgraph/js" has not been loaded yet for context: _. Use require([])

it's kinda too bad, I can use what you call v1, but it has limitations that I've seen fixed in v2 (like the way branches are labeled), so I'd really be eager to give v2 a try, but am totally stuck at this point 

any hint would be most welcome - thanks !

**Comment by nicoespeon** [comment]
@enlait @parmentelat I just released a version of `@gitgraph/js` with a browser bundle.

Can you please try the instructions I described in the README: https://github.com/nicoespeon/gitgraph.js/tree/master/packages/gitgraph-js#example-with-browser-bundle

Let me know if that works for you.

If so, the next steps are:
- [ ] Update the website with instructions
- [ ] Put the release on CDN.js

**Comment by enlait** [comment]
Tried it with nginx instead of npx (gitgraph.umd.min.js and html in current directory):
`docker pull nginx && docker run -v $(pwd):/usr/share/nginx/html -p 8080:80 nginx`

Seems to work just fine.

**Comment by parmentelat** [comment]
Hi @nicoespeon 

thanks for taking the time to put this together  
now at least I am able to write a simple standalone page that works

I'm still struggling to get this to work from within a Jupyter environment; the way I had been able to do that with gitgraphv1 is not working with this bundle, I'll probably need a bit more time to figure out what's going on here.

I'll try to report on this page when/if I make progress with that.

**Comment by zapp42** [comment]
Hi @nicoespeon,

sorry for not testing #287 earlier, I did not find the time. It works for me now, too.

Thanks,
Rolf

**Comment by nicoespeon** [comment]
Documentation have been added to `@gitgraph/js` README.

As for the CDN, you can use one of the following:

- jsDelivr <https://cdn.jsdelivr.net/npm/@gitgraph/js>
- unpkg <https://unpkg.com/@gitgraph/js>

Also, I created a CodePen playground to illustrate: https://codepen.io/nicoespeon/pen/arqPWb?editors=1010
