### ISSUE TITLE
Missing documentation for gitgraphjs (v1)

### ISSUE THREAD

**Issue by enlait** [nicoespeon/gitgraph.js#284]
Documentation for v1 seems to be gone(?).

Could you please direct to a repo revision with api documentation?

**Comment by nicoespeon** [comment]
Hi @enlait 👋 

Good point, v1 is deprecated but still usable. I put back the doc & examples of v1 at https://gitgraphjs.com/v1

Let me know if you have any issue with it, but everything should have followed properly.
