### ISSUE TITLE
Allow multiple branches in the same column

### ISSUE THREAD

**Issue by ghost** [nicoespeon/gitgraph.js#290]
Hi! First, thanks for the great git-drawing solution, it really rocks! Second, there is a problem.

I need to draw a repo with many short-lived feature branches. They created from and merged back to develop almost consequently and there are a lot of them. The idea is quite similar to [the compact mode example](https://gitgraphjs.com/stories/?path=/story/gitgraph-js-1-basic-usage--compact-mode) in the storybook, but with many more branches.

The problem is that every branch is drawn in its own column (just like in the compact mode example). Even if the branch is merged and has no further commits, I can't reuse it's column and there is no way to draw some other branch in that column. Customizing the branch order with `compareBranchesOrder` doesn't help, because even if it returns 0, the branches are still drawn in the different columns. In version 1 I could specify an exact column number to draw the branch to. In version 2 I can't find a way to do that.

Am I missing something or it's currently impossible in the version 2?

**Comment by marekyggdrasil** [comment]
I think this visualises the problem pretty well.

<img width="486" alt="Screenshot 2019-09-10 at 11 48 04 AM" src="https://user-images.githubusercontent.com/8202674/64582714-fc34a180-d3c0-11e9-8f1e-9849f62ae5d9.png">

The columns are not being reused. When new branch gets created it gets assigned a new column, after this branch gets merged this column is blocked and no new branch could occupy it.

**Comment by dhiahassen** [comment]
is this implemented ? i would like to use it , thanks

**Comment by marekyggdrasil** [comment]
@dhiahassen it is not yet implemented, requires a possibility to customize the rendering algorithm which is an ongoing work in PR https://github.com/nicoespeon/gitgraph.js/pull/364 and https://github.com/marekyggdrasil/gitgraph.js/pull/1, work is a bit slow, you are welcome to help out and contribute!
