### ISSUE TITLE
Merging branch back should not create a commit, but fast-forward instead

### ISSUE THREAD

**Issue by parmentelat** [nicoespeon/gitgraph.js#293]
**Describe the bug**
in some configurations, merging 2 git branches does not result in an extra commit being created.

**To Reproduce**

start from this situation
![image](https://user-images.githubusercontent.com/4519227/57364561-bc944980-7183-11e9-990b-17a40b8d215a.png)

and then do `devel.merge(master); `

you will end with this
![image](https://user-images.githubusercontent.com/4519227/57364627-e0578f80-7183-11e9-9bc9-fcfa5e719e61.png)

**Expected behavior**
I would expect to see this instead 

![image](https://user-images.githubusercontent.com/4519227/57364745-16950f00-7184-11e9-9d6f-835bb4132c2d.png)

Of course I may be the one missing something here; please let me know if there's a simple way to achieve this result.

**Comment by nicoespeon** [comment]
Hi @parmentelat 👋 

In that case, the behaviour is the one expected. A merge would always create a merge commit—unless it's a fast-forward.

What you want to achieve is to rebase the `devel` branch onto the `master` branch. We don't provide a `rebase()` method yet, but that could be a feature to consider indeed. I don't think what you want to achieve is doable with current features—but I won't say it's a bug with merge.

**Comment by parmentelat** [comment]
Sent from my iPhone

> On 9 May 2019, at 03:37, Nicolas Carlo <notifications@github.com> wrote:
> 
> A merge would always create a merge commit—unless it's a fast-forward.

How much more fast-forward can a merge be than this one ?

**Comment by parmentelat** [comment]
having seen in another issue that you apparently consider gitgraph.js should behave like git log and mainstream UIs, I would definitely consider this a bug; but that's just me I guess :)

**Comment by fabien0102** [comment]
Indeed git fast-forward this kind of case by default

![image](https://user-images.githubusercontent.com/1761469/57445870-90e09480-7253-11e9-805a-4dfb614de239.png)

Good catch 👍

**Comment by nicoespeon** [comment]
@parmentelat my bad, I was wrong. I thought that this was git behavior, but Today I Learned it does what you said should be expected—thank you for sharing this.

Changing the issue back to a bug and we'll fix it 👍
