### ISSUE TITLE
How to display branch label on all commits?

### ISSUE THREAD

**Issue by IsaacHub** [nicoespeon/gitgraph.js#294]
I have this:
```
<div id="gitgraph"></div>
```

```
 const graphOptions ={
 orientation:'vertical-reverse'
 }
    const graphContainer = document.getElementById("gitgraph");

    const gitgraph = GitgraphJS.createGitgraph(graphContainer,graphOptions);

    const master = gitgraph.branch("master");
    master.commit("Initial commit");

    const develop = gitgraph.branch("develop");
    develop.commit("Add TypeScript");

    const aFeature = gitgraph.branch("a-feature");
    aFeature
      .commit("Make it work")
      .commit("Make it right")
      .commit("Make it fast");

    develop.merge(aFeature);
    develop.commit("Prepare v1");

    master.merge(develop).tag("v1.0.0");
```

[
![gitgraphissue](https://user-images.githubusercontent.com/20126441/57625240-16947500-75b1-11e9-810d-9a8727739cbd.PNG)
](url)

**As you can see branch labels not appearing on all commits, but I want the branch labels on all commits. How to achieve that?** 
Here is the [fiddle](https://jsfiddle.net/iselwin/L8x6umz4/3/)

**Comment by nicoespeon** [comment]
Hi @IsaacHub 👋 

That's a good question. I'm not 100% sure you can do it, but you might be able to provide a custom `renderMessage` to commit options. This way, you might be able to include the branch name for every commit. But it might not be very convenient to do…

I'm wondering if we should include the branch name on every commit by default. This is what we did at first, but I decided not to and to put the branch name only where the branch is pointing instead. 

I'm open to discussion and feedback on usage. So this is an open question to anyone: would you usually prefer having the branch name on every commit? Can you explain why?

Thanks 🙏

**Comment by IsaacHub** [comment]
Yes. We prefer having the branch name on every commit. Because WE NEED IT. You should consider adding a new option to the library in the next patch release or minor release so that we can write something like
```
 const graphOptions = {
    orientation : 'vertical-reverse',
    branchNameOnEveryCommit : true
 }
```
By default your library can ship with `branchNameOnEveryCommit` set to `false`. Let the user decide the display of branch names while initiating the graph. As simple as that. Make sense?

_More configurable usability of a library is the real success._

**Comment by IsaacHub** [comment]
Comment out these lines to display branch name on all commits

```
/*const commitHash = gitgraph.refs.getCommit(branch.name);
if (commit.hash !== commitHash) return null;*/
```

https://github.com/nicoespeon/gitgraph.js/blob/ed9ede4bfa629c07407cb685a30b42a00d037ac0/packages/gitgraph-js/src/gitgraph.ts#L428

**Comment by nicoespeon** [comment]
The graph options seems a reasonable approach indeed. I think we can do that. I'll talk with Fabien on Thursday and we might get this done together the same day. 

Will keep you posted @IsaacHub, thanks for the suggestion 👍

**Comment by nicoespeon** [comment]
@IsaacHub I've got great news: we added an option to do this in version v1.4.0 of both `@gitgraph/js` and `@gitgraph/react` packages.

You can use the following option when you create the graph to activate:

https://github.com/nicoespeon/gitgraph.js/blob/4f85de4702881326520a1efcd11a221835eb9031/packages/stories/src/gitgraph-react/1-basic-usage.stories.tsx#L215

Thanks for your suggestion 👍
