### ISSUE TITLE
Is there an implementation with the GitHub API or using a .git directly?

### ISSUE THREAD

**Issue by siddhant1999** [nicoespeon/gitgraph.js#300]
I'm using the GitHub API to get my commit history for a project with 4000+ commits and can't use manual function calls like:

master
  .commit("Add README")
  .commit("Add tests")
  .commit("Implement feature");

Has anyone implemented this or can point me somewhere?

Apologies for abusing github issues

**Comment by nicoespeon** [comment]
Hi @siddhant1999 👋 

It's still a bit experimental, but here's what you can do:

- Use [git2json](https://github.com/fabien0102/git2json) to generate a JSON from your git repository
- Use `gitgraph.import()` to generate the graph

See following stories that illustrates it:  

https://github.com/nicoespeon/gitgraph.js/blob/4f85de4702881326520a1efcd11a221835eb9031/packages/stories/src/gitgraph-react/4-imports.stories.tsx#L12-L16

https://github.com/nicoespeon/gitgraph.js/blob/4f85de4702881326520a1efcd11a221835eb9031/packages/stories/src/gitgraph-js/4-imports.stories.tsx#L15-L17

I don't think we tried it on such large graphs. You might want to render only a part of it. If so, there is an ongoing discussion on how to do that: https://github.com/nicoespeon/gitgraph.js/issues/215#issuecomment-486700869

Let me know if that solves your case 😉
