### ISSUE TITLE
Compat Mode not working when importing git2json data

### ISSUE THREAD

**Issue by Symbolk** [nicoespeon/gitgraph.js#304]
**Describe the bug**

I am using the git2json to get the commit history data and `@gitgraph/js`  to render the graph. However, when I create the graph from the simulated commits, the compact mode works fine so it renders commit messages in tooltips, but when I replace the data with what's returned from git2json, it renders commit messages BOTH in tooltips and on the right side of the commit node.

**To Reproduce**

```javascript
    let options = {
        mode: GitgraphJS.Mode.Compact
      }
      const gitgraph = GitgraphJS.createGitgraph(graphContainer, options)

      const git2json = require('@fabien0102/git2json')

      // Simulate git commands with Gitgraph API.
      // const master = gitgraph.branch('master')
      // master.commit('Initial commit')

      // const develop = gitgraph.branch('develop')
      // develop.commit('Add TypeScript')

      // const aFeature = gitgraph.branch('a-feature')
      // aFeature
      //   .commit('Make it work')
      //   .commit('Make it right')
      //   .commit('Make it fast')

      // develop.merge(aFeature)
      // develop.commit('Prepare v1')

      // master.merge(develop).tag('v1.0.0')

      git2json.run().then(myGitLogJSON => {
        gitgraph.import(myGitLogJSON)
      })
```

**Expected behavior**

The commit message should be rendered in tooltips.

**Screenshots**

![image](https://user-images.githubusercontent.com/14107297/61128320-2dd5dd00-a4e4-11e9-80d3-8be2585ee3b5.png)

**Context**

- gitgraph/js
- imported from the CDN: https://cdn.jsdelivr.net/npm/@gitgraph/js
- Inside a vue-electron app.

**Comment by nicoespeon** [comment]
Interesting. Thanks for the detailed bug, I'll have a look this weekend.

**Comment by nicoespeon** [comment]
Found the issue, fix incoming.

Thanks for spotting @Symbolk. The issue was really helpful 👍

**Comment by nicoespeon** [comment]
A patch is being deployed including this fix 👌

**Comment by Symbolk** [comment]
@nicoespeon I recently developed a tool (https://github.com/Symbolk/SmartCommit ) with the `gitgraph` as one component, thanks for the nice lib!
