### ISSUE TITLE
Gitgraph react component does not react to children/props changes

### ISSUE THREAD

**Issue by levic** [nicoespeon/gitgraph.js#318]
This is related to #288 - but it doesn't really matter whether you use `graph` or `children`, `GitGraph` does not react to property changes.

Demo: https://codesandbox.io/s/gitgraph-react-render-ignoring-dependency-changes-55ko6

If you remove (or rename) the `key` property then the graph will not change. This happens both when passing the graph as a prop (see `AppUsingProp`) or as a build function (see `AppUsingChildren`).

The underlying cause is that as an optimisation React will try to reuse existing components where possible and simply change their state/props. `GitGraph.constructor` stores a copy of the `GitGraphCore` instance as a regular object property and never updates it, so changing the `graph` property or `children` doesn't cause any visible change. The demo works with `key` because you are explicitly telling React not to reuse any previous component unless it has the same `key`.

It might be that this is intended for performance reasons to prevent a lot of recalculation, but if so then the documentation should probably indicate this and suggest the `key` workaround (I couldn't find anything about this).

In particular, you could potentially avoid rerendering if the `graph` property doesn't change, but when using the callback method `GitGraph` can't know whether the callbakc is always going to return the same result so the most correct behaviour is to recreate a new graph on every rerender (and since the default hash function is random will probably result in a full rerender anyway).

**Comment by starrett67** [comment]
Thank you so much for this post. Just save me a lot of time.

**Comment by iq180fq200** [comment]
Thank you so much for this post. Also save me a lot of time.

**Comment by oRyoma** [comment]
Thanks your this post !
