### ISSUE TITLE
Use hash as key instead hashAbbrev in @gitgraph/react

### ISSUE THREAD

**Issue by soumyart** [nicoespeon/gitgraph.js#321]
**Describe the bug**
While rendering commits, gitgraph-react uses hashAbbrev as key, which is a truncated version of commit hash. Different commit hash with same prefix returns same hashAbbrev. Which leads to same key panic error in react.

https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-react/src/Gitgraph.tsx#L217

Every server/database can't produce git like commit hash.

**To Reproduce**
Provide different string having same initials as commit hash.
Ex.
```javascript
master.commit({hash: "5c7fb1924868ac6d7e45430a"});
master.commit({hash: "5c7fb1924868ac1a0b45430b"});
```

https://codesandbox.io/s/gitgraph-react-same-key-error-x3j3b

**Expected behavior**

There shouldn't be any error on console.

**Screenshots**

![image](https://user-images.githubusercontent.com/20027561/63632985-a9d45080-c65e-11e9-9716-70f90caed1fb.png)

**Context**

- Library  `@gitgraph/react`
- version 1.5.1

**Additional information**

**Comment by nicoespeon** [comment]
@all-contributors please add soumyart for bug
