### ISSUE TITLE
Passing parentCommit to a new branch commit does not have any effect on which commit the branch is branched from

### ISSUE THREAD

**Issue by lhobbs22** [nicoespeon/gitgraph.js#327]
I am using GitGraphjs to display branches and commits.

In this scenario below, I have a branch that is branched from the second commit in master (where the arrow is) - the parentCommit value passed is of the correct parentCommit (the second) however the commit is appearing as branched from the third commit

![gitgraph error](https://user-images.githubusercontent.com/3855377/66107840-24c34c00-e5b9-11e9-8f3d-198832a150ca.jpg)

I am building the graph programatically using the code below

```javascript
graphContainer = document.getElementsByClassName('graph-container')[0];
gitgraph = GitgraphJS.createGitgraph(graphContainer, options);
results = JSON.parse(data[0]);

$.each(results, function(index, value) {
    var currentBranch = gitgraph.branch(Object.keys(value)[0]);
    branchName = Object.keys(value)[0];
    commitSha = Object.values(value)[0][0];
    commitTitle = Object.values(value)[0][1];
    commitAuthor = Object.values(value)[0][2];
    commitParent = Object.values(value)[0][3];
    currentBranch.commit({
        subject: commitTitle,
        sha1: commitSha,
        author: commitAuthor,
        parentCommit: commitParent,
        onClick() {
            window.location.href = Object.values(value)[0][4];
        }
    });
});
```

I am not sure if I am doing something wrong here, if there is another way to get a branch to branch from a specific commit, or if there is a bug in gitgraph

**Comment by marekyggdrasil** [comment]
Hi @lhobbs22 👋🏻, could you provide the input JSON which is being processed in the provided code? It is required to reproduce your problem. I suspect the issue is the order of commits but cannot say for sure until I see the input.

**Comment by lhobbs22** [comment]
Hi @marekyggdrasil, here is my input JSON (apologies it isn't formatted nicely)

`["[{\"master\":[\"c136dee6-1eb4-6067-cbd6-321ace98101e\",\"another experiment\",\"Leanne Hobbs\",null,\"/commit_refs/6?branch_id=1\"]},{\"master\":[\"565e5c9c-49b1-de2e-0eac-cf84620a9bbd\",\"sdf\",\"dfghjk fhgfghfj\",{\"id\":6,\"sha\":\"c136dee6-1eb4-6067-cbd6-321ace98101e\",\"title\":\"another experiment\",\"location\":\"sdf\",\"date_stocked\":\"2019-05-07T00:00:00.000Z\",\"obtained_from\":\"sdf\",\"references\":\"sdf\",\"user_id\":1,\"created_at\":\"2019-10-17T15:24:08.397Z\",\"updated_at\":\"2019-10-17T15:24:08.397Z\",\"strain_id\":null,\"deleted_at\":null,\"branch_id\":1,\"media\":[],\"barcode\":\"C8DBCEC17FBF62CC84FE791E924C7258\",\"barcode_generated\":false,\"barcode_added\":true,\"state\":\"editable\"},\"/commit_refs/7?branch_id=1\"]},{\"testing branch\":[\"1eb76fa2-6108-61ba-ad24-db1cdbfafe8f\",\"experimental commit\",\"Leanne Hobbs\",{\"id\":4,\"sha\":\"09b9a512-8351-65a2-b787-8308830a7851\",\"title\":\"sdfΔfdsfds::fds\",\"location\":\"sdf\",\"date_stocked\":\"2019-05-07T00:00:00.000Z\",\"obtained_from\":\"\",\"references\":\"sdf\",\"user_id\":1,\"created_at\":\"2019-10-16T12:59:25.868Z\",\"updated_at\":\"2019-10-16T12:59:25.868Z\",\"strain_id\":null,\"deleted_at\":null,\"branch_id\":1,\"media\":[],\"barcode\":\"C8DBCEC17FBF62CC84FE791E924C7258\",\"barcode_generated\":false,\"barcode_added\":true,\"state\":\"editable\"},\"/commit_refs/5?branch_id=2\"]},{\"master\":[\"10478d29-dbe1-c227-46d1-5aab24986b16\",\"sdf\",\"Leanne Hobbs\",{\"id\":7,\"sha\":\"565e5c9c-49b1-de2e-0eac-cf84620a9bbd\",\"title\":\"sdf\",\"location\":\"sdf\",\"date_stocked\":\"2019-05-07T00:00:00.000Z\",\"obtained_from\":\"sdf\",\"references\":\"sdf\",\"user_id\":2,\"created_at\":\"2019-10-17T15:22:24.120Z\",\"updated_at\":\"2019-10-17T15:22:24.175Z\",\"strain_id\":null,\"deleted_at\":null,\"branch_id\":1,\"media\":[{\"url\":\"/uploads/commit_ref/media/7/Screenshot_2019-09-05_at_16.45.43.png\"}],\"barcode\":\"C8DBCEC17FBF62CC84FE791E924C7258\",\"barcode_generated\":false,\"barcode_added\":true,\"state\":\"editable\"},\"/commit_refs/1?branch_id=1\"]},{\"master\":[\"1ff2c82c-558c-9995-ee09-7548200ab9bb\",\"dfsgdfsggΔ::\",\"Leanne Hobbs\",{\"id\":1,\"sha\":\"10478d29-dbe1-c227-46d1-5aab24986b16\",\"title\":\"sdf\",\"location\":\"sdf\",\"date_stocked\":\"2019-05-07T00:00:00.000Z\",\"obtained_from\":\"sdf\",\"references\":\"sdf\",\"user_id\":1,\"created_at\":\"2019-10-16T13:08:00.415Z\",\"updated_at\":\"2019-10-16T13:08:00.415Z\",\"strain_id\":null,\"deleted_at\":null,\"branch_id\":1,\"media\":[],\"barcode\":\"C8DBCEC17FBF62CC84FE791E924C7258\",\"barcode_generated\":false,\"barcode_added\":true,\"state\":\"finalised\"},\"/commit_refs/3?branch_id=1\"]},{\"master\":[\"09b9a512-8351-65a2-b787-8308830a7851\",\"sdfΔfdsfds::fds\",\"Leanne Hobbs\",{\"id\":3,\"sha\":\"1ff2c82c-558c-9995-ee09-7548200ab9bb\",\"title\":\"dfsgdfsggΔ::\",\"location\":\"sdf\",\"date_stocked\":\"2019-05-07T00:00:00.000Z\",\"obtained_from\":\"sdf\",\"references\":\"sdf\",\"user_id\":1,\"created_at\":\"2019-10-16T13:08:00.187Z\",\"updated_at\":\"2019-10-16T13:08:00.187Z\",\"strain_id\":null,\"deleted_at\":null,\"branch_id\":1,\"media\":[],\"barcode\":\"C8DBCEC17FBF62CC84FE791E924C7258\",\"barcode_generated\":false,\"barcode_added\":true,\"state\":\"editable\"},\"/commit_refs/4?branch_id=1\"]}]","[\"testing branch\",\"master\"]"]`

**Comment by marekyggdrasil** [comment]
Hey @lhobbs22, thanks for sharing the JSON. I don't think it is the same one as one used to generate the output on screenshot in the first issue (commits "first commit", "second commit" etc are not there).

I created this codepen to help reproduce the issue, feel free to modify it.

https://codepen.io/marekyggdrasil/pen/wvvdKOm

**Comment by lhobbs22** [comment]
Closing issue as no longer using this library for git graph rendering
