### ISSUE TITLE
cant add html to commit messages

### ISSUE THREAD

**Issue by kstych** [nicoespeon/gitgraph.js#329]
**Describe the bug**

hi, i am trying to add button and links before commit messages but i am getting html printed as text (escaped)

is there an alternative method or workaround? I want to have styled buttons/ divs and links before or in between commit messages

**To Reproduce**

set a commit message to any html  "<a href=#>test</a>"

**Expected behavior**

should render the html

thankyou!

**Comment by marekyggdrasil** [comment]
Hi @kstych 👋🏻,

I am aware of the problem you mentioned, the title and body provided to commits is not being rendered. Have you tried passing a custom render function as parameter in `options`?

Example custom rendering function:

https://github.com/nicoespeon/gitgraph.js/blob/b73ce455d955197c3f5dde62e37fbb7b30a530d2/packages/stories/src/gitgraph-js/6-custom-renders.stories.tsx#L159-L165

How to pass it in the parameters:

https://github.com/nicoespeon/gitgraph.js/blob/b73ce455d955197c3f5dde62e37fbb7b30a530d2/packages/stories/src/gitgraph-js/6-custom-renders.stories.tsx#L174-L177

Let me know if that helps!

**Comment by kstych** [comment]
hi @marekyggdrasil 

thanks for the references.. yes I did tried these and any html inside the "content" of "createText" just printed out as plain text

**&lt;div class='label label-success'&gt;test hrml&lt;/div&gt; 5051848 - initial commit**

**Comment by marekyggdrasil** [comment]
Ok I think I know what's going on. We should use `createForeignObject` instead of `createText` but it won't help as inside of the `createForeignObject` we assign content to `.textcontent` property.

https://github.com/nicoespeon/gitgraph.js/blob/5075bb81652b82d6815747dc69703f345e807e52/packages/stories/src/helpers.tsx#L229-L231

Property [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) is not style aware. In order to render HTML within commit messages we would need to use `.innerHTML` instead.

I suggest adding an extra option such as 

```javascript
const renderHTMLCommit: CommitOptions["renderMessage"] = (commit) => {
    return createForeignObject({
        content: `<div class="hash">${commit.hashAbbrev}</div> - <div class="subject">${commit.subject}</div>`,
        html: true,
    });
};
master.commit({
    subject: "Do something crazy",
    renderMessage,
});
```
This would allow to create create commits with embedded HTML elements which would be interpreted by the browser. Looks like currently it is not supported but we should definitely add this possibility, I remember myself using it in `V1` fairly often.

@nicoespeon any thoughts?

**Comment by kstych** [comment]
hi @marekyggdrasil ,

yes createForeignObject works, i tried with a custom version of createForeignObject and it produced html using "innerHTML" property, 

i am closing this as the workaround is more then sufficient using createForeignObject

thankyou for your help

**Comment by marekyggdrasil** [comment]
@kstych can you paste a JS code that renders HTML commits? I think that might be useful for others and I also think about adding it to the tutorial. Thanks.

**Comment by kstych** [comment]
sure here goes

`function createForeignObjectHTML(
  options: ForeignObjectOptions,
): SVGForeignObjectElement {
  const result = document.createElementNS(SVG_NAMESPACE, "foreignObject");
  result.setAttribute("width", options.width.toString());

  if (options.translate) {
    result.setAttribute("x", options.translate.x.toString());
    result.setAttribute("y", options.translate.y.toString());
  }

  const div = document.createElement("div");
  div.innerHTML = options.content;
  result.appendChild(div);

  return result;
}

const renderMessage: CommitOptions["renderMessage"] = (commit) => {
    return createForeignObjectHTML({
        content: `<div class="hash">${commit.hashAbbrev}</div> - <div class="subject">${commit.subject}</div>`,
    });
};

master.commit({
    subject: "Do something crazy",
    renderMessage,
});
`

**Comment by Meywether** [comment]
Hello, thanks for this great library,
I have some problems to transfer your example into TS ->
![image](https://user-images.githubusercontent.com/39849054/71677524-58ae3900-2d83-11ea-9858-66c2212e4ffb.png)

It says, that ForeignObjectOptions, could not be found, the same for SVG_NAMESPACE.

Do you have any advice for me ?

Thanks in advance !!!!!

Best regards
Meywether

**Comment by byzheng** [comment]
> sure here goes
> 
> ```js
> function createForeignObjectHTML(
>   options: ForeignObjectOptions,
> ): SVGForeignObjectElement {
>   const result = document.createElementNS(SVG_NAMESPACE, "foreignObject");
>   result.setAttribute("width", options.width.toString());
> 
>   if (options.translate) {
>     result.setAttribute("x", options.translate.x.toString());
>     result.setAttribute("y", options.translate.y.toString());
>   }
> 
>   const div = document.createElement("div");
>   div.innerHTML = options.content;
>   result.appendChild(div);
> 
>   return result;
> }
> 
> const renderMessage: CommitOptions["renderMessage"] = (commit) => {
>     return createForeignObjectHTML({
>         content: `<div class="hash">${commit.hashAbbrev}</div> - <div class="subject">${commit.subject}</div>`,
>     });
> };
> 
> master.commit({
>     subject: "Do something crazy",
>     renderMessage,
> });
> ```

I would to use it in the js for html page. Is any guideline to use it?

Thanks.
