### ISSUE TITLE
Commit options in a merge do not seem to work

### ISSUE THREAD

**Issue by jabiercoding** [nicoespeon/gitgraph.js#337]
**Describe the bug**
I am trying to do something like this
master.merge(develop, { subject: "Add feature" });
but it is not adding the subject. The same happens with hash etc.

You can try with
https://codepen.io/nicoespeon/pen/arqPWb?editors=1010
just replacing develop.merge(aFeature);
with develop.merge(aFeature, {subject: "The subject" });

**Comment by nicoespeon** [comment]
@edwardwall is right indeed, using either one of the proposed option will work.
