### ISSUE TITLE
BranchUserApi.checkout() doesn't update the HEAD ref

### ISSUE THREAD

**Issue by richteambs** [nicoespeon/gitgraph.js#345]
After calling `mybranch.checkout()` the `HEAD` ref is unaffected. HEAD should always point to the latest commit in the current branch (unless in detached head mode). 

**To Reproduce**

https://codepen.io/richtea43/pen/abOdRzr?editors=0010

**Expected behavior**

The HEAD ref should always point to the latest commit in the current branch (unless in detached head mode). Anyone using git would expect HEAD to be set after a checkout.

**Context**

- Which library is impacted? `@gitgraph/core` 
- Which version of the library is it? Latest code in master branch
- What browser and version is impacted? N/A

**Additional information**

The code for commit is [here](https://github.com/nicoespeon/gitgraph.js/blob/5ea521c45d7fc0222e153b8161a10546d24af608/packages/gitgraph-core/src/user-api/branch-user-api.ts#L196) - it doesn't update HEAD. The only time HEAD is updated is when committing (see [here](https://github.com/nicoespeon/gitgraph.js/blob/5ea521c45d7fc0222e153b8161a10546d24af608/packages/gitgraph-core/src/user-api/branch-user-api.ts#L240)).

**Comment by richtea** [comment]
Apologies, I accidentally used my work account to open this issue - if I have time, I will send a PR from my personal GitGub account (this one).
