### ISSUE TITLE
"Cannot read property 'spacing' of undefined" when using templates

### ISSUE THREAD

**Issue by nZeus** [nicoespeon/gitgraph.js#358]
**Describe the bug**
Not possible to use templates.
`Cannot read property 'spacing' of undefined` is thrown.

**To Reproduce**
```js

const gitgraph = createGitgraph(graphContainer, {
    template: {
        commit: {
            message: {
                displayAuthor: false
            }
        }
    }
});

const develop = gitgraph.branch("develop");
develop.commit("Add TypeScript");
```

**Expected behavior**
No errors should be thrown

**Screenshots**
![Screenshot from 2020-05-11 00-04-05](https://user-images.githubusercontent.com/2727326/81511630-f8279d80-931a-11ea-80bf-2413419a6546.png)

**Context**

- Which library is impacted? `@gitgraph/js`
- Which version of the library is it? `1.3.5`
- What browser and version is impacted? latest Chromium

**Comment by fabien0102** [comment]
Hello,
this is totally expected, you need to use the `templateExtend` function to create a new template or provide all the values.

You have a good example of the usage in our storybook:
https://github.com/nicoespeon/gitgraph.js/blob/46a98c9f145224d0c41afb472b5580bc4644aaa1/packages/stories/src/gitgraph-js/5-templates.stories.tsx#L73-L83

PS: I like this "Add Typescript" commit in the example 😁
