### ISSUE TITLE
Go back to a specific commit by Id, then put on another action, like branch out

### ISSUE THREAD

**Issue by queeeentin** [nicoespeon/gitgraph.js#360]
Is there a way that we can go back to a committed commit on a branch then perform an action on the commit, like create a branch.

**Comment by albertdev** [comment]
I was worried that parallel branching might be difficult when I first read this issue, but it seems this is not a problem as long as you create a branch at the right time.

You can then assign it to a variable and keep that variable around, then later add commits to that branch. After all this is just a simulation of git history, you can play with the scenario to make it work.
