### ISSUE TITLE
Why my svg width cannot fit the container?

### ISSUE THREAD

**Issue by Rain120** [nicoespeon/gitgraph.js#367]
**Describe the bug**

Why my svg width cannot fit the container?

![image](https://user-images.githubusercontent.com/20939839/84987383-9c023580-b172-11ea-80ec-48c0ea936c9d.png)

**To Reproduce**

[codesandbox](https://codesandbox.io/s/react-git-graph-5sbeq?file=/src/SimpleGraph.tsx)

**Screenshots**

![image](https://user-images.githubusercontent.com/20939839/84987182-4a59ab00-b172-11ea-823a-df52427bc3a1.png)

**Comment by ahmeed83** [comment]
I have the same issue_

**Comment by Rain120** [comment]
I had try to fixed it, but I cannot run it at my local, so I forgave it.

**Comment by crutchcorn** [comment]
I strongly suspect this issue is related to:

#389

Is there any way you can remove the `StrictMode` and tell me if it works? (I have a PR to fix this bug if that is the case)

**Comment by Rain120** [comment]
@crutchcorn 

Demo Here [codesandbox](https://codesandbox.io/s/react-git-graph-5sbeq?file=/src/index.js:868-970)

### Before

![image](https://user-images.githubusercontent.com/20939839/100066411-07fa6f80-2e70-11eb-907d-f730b5110ee3.png)

### After

![image](https://user-images.githubusercontent.com/20939839/100066457-16e12200-2e70-11eb-8e10-52f6900a9e68.png)

### Summary

It looks like the bug has fixed. But Why? How to fixed? May I get your commit history which fix it?

**Comment by crutchcorn** [comment]
This is fantastic, it means that once #389 is merged in (which should likely be soon, as my other React refactor [which was a much larger change] was merged in today) you simply need to update the NPM package and it'll fix the issue for you and you can re-enable strict mode

If you're curious for the _why_, I included an explanation in the linked PR that outlined why this happened and how I fixed it

**Comment by Rain120** [comment]
@crutchcorn 

ok, I have seen more info from the link, thx for your explanation
