### ISSUE TITLE
React-Native support

### ISSUE THREAD

**Issue by Shing-Ho** [nicoespeon/gitgraph.js#370]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when […]
It's great to use `gitgraph.js` and I loved to use it.
But there's no react-native feature. Is there any person who can implement `react-native` feature for this `gitgraph.js`?
I hope to use `gitgraph.js` in `expo` project

**Comment by crutchcorn** [comment]
I'm going to be taking a stab at this on-stream today in an hour!

twitch.tv/crutchcorn

I'll make a PR if I can manage to get this working
