### ISSUE TITLE
Hello, boss. There is something wrong with the import method rendering

### ISSUE THREAD

**Issue by applelizihao** [nicoespeon/gitgraph.js#378]
### Help!
![image](https://user-images.githubusercontent.com/47731529/91537897-9468c500-e949-11ea-8ad5-10aca69384c0.png)

Hello, boss. There is something wrong with the import method rendering

**Comment by fabien0102** [comment]
Hello, can you define "something" and add a bit more details about how to repro?

Thanks 🙂

**Comment by applelizihao** [comment]
Thank you for your busy schedule to see my reply！
There is something wrong with the color and order of the branch. The gray line should be the master, and the master line should not be changed. This is JSON data

**Comment by applelizihao** [comment]
[
  {
    "refs": [
      "master"
    ],
    "hash": "8aef8fadd9f0756da7939cc61a964390e347ec57",
    "hashAbbrev": "8aef8fa",
    "tree": "2ba3ce9532abe708c37d52d255afeb1bc34a8a58",
    "treeAbbrev": "2ba3ce9",
    "parents": [
      "2de6d5f75365de917ade92e83920ac18114063e7"
    ],
    "parentsAbbrev": [
      "2de6d5f"
    ],
    "author": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600631000
    },
    "committer": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600631000
    },
    "subject": "m2",
    "body": "",
    "notes": "",
    "stats": [
      {
        "additions": 0,
        "deletions": 0,
        "file": "a.ss"
      }
    ]
  },
  {
    "refs": [
      "HEAD",
      "dev"
    ],
    "hash": "f246bbf6cd344cb273c4d48861bf1a20f9c0d018",
    "hashAbbrev": "f246bbf",
    "tree": "6d11b8ea56b4d7e3b76363997adebf12003ca6f1",
    "treeAbbrev": "6d11b8e",
    "parents": [
      "2627127d5e2757a4ab7206589dcefd2df889c6c8"
    ],
    "parentsAbbrev": [
      "2627127"
    ],
    "author": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600587000
    },
    "committer": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600587000
    },
    "subject": "d2",
    "body": "",
    "notes": "",
    "stats": [
      {
        "additions": 38,
        "deletions": 0,
        "file": "1.txt"
      },
      {
        "additions": 38,
        "deletions": 0,
        "file": "src/App.vue"
      }
    ]
  },
  {
    "refs": [],
    "hash": "2627127d5e2757a4ab7206589dcefd2df889c6c8",
    "hashAbbrev": "2627127",
    "tree": "9272b93d73f63bb87b6cda22f4059c79a3e6f7fa",
    "treeAbbrev": "9272b93",
    "parents": [
      "0ff219703f8203869623f2c187bb49af86ecfae0"
    ],
    "parentsAbbrev": [
      "0ff2197"
    ],
    "author": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600461000
    },
    "committer": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600461000
    },
    "subject": "d1",
    "body": "",
    "notes": "",
    "stats": [
      {
        "additions": 52,
        "deletions": 3,
        "file": "1.txt"
      },
      {
        "additions": 188,
        "deletions": 135,
        "file": "src/App.vue"
      }
    ]
  },
  {
    "refs": [],
    "hash": "0ff219703f8203869623f2c187bb49af86ecfae0",
    "hashAbbrev": "0ff2197",
    "tree": "abd3031c4c944adbb0ac27d3721da09a99ebffbe",
    "treeAbbrev": "abd3031",
    "parents": [
      "3cc6909525a3c7ac229c076eda2ba14cf7d183c5"
    ],
    "parentsAbbrev": [
      "3cc6909"
    ],
    "author": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600297000
    },
    "committer": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598600297000
    },
    "subject": "dev",
    "body": "",
    "notes": "",
    "stats": [
      {
        "additions": 138,
        "deletions": 0,
        "file": "1.txt"
      },
      {
        "additions": 18,
        "deletions": 0,
        "file": "package-lock.json"
      },
      {
        "additions": 2,
        "deletions": 0,
        "file": "package.json"
      },
      {
        "additions": 156,
        "deletions": 21,
        "file": "src/App.vue"
      }
    ]
  },
  {
    "refs": [],
    "hash": "2de6d5f75365de917ade92e83920ac18114063e7",
    "hashAbbrev": "2de6d5f",
    "tree": "e80f6f16f9b148e8e824223acd9dd9e02f8e4f20",
    "treeAbbrev": "e80f6f1",
    "parents": [
      "3cc6909525a3c7ac229c076eda2ba14cf7d183c5"
    ],
    "parentsAbbrev": [
      "3cc6909"
    ],
    "author": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598599297000
    },
    "committer": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1598599297000
    },
    "subject": "m1",
    "body": "",
    "notes": "",
    "stats": [
      {
        "additions": 129,
        "deletions": 12,
        "file": "package-lock.json"
      },
      {
        "additions": 4,
        "deletions": 1,
        "file": "package.json"
      },
      {
        "additions": 26,
        "deletions": 18,
        "file": "src/App.vue"
      },
      {
        "additions": 24,
        "deletions": 0,
        "file": "src/dist/main.dev.js"
      },
      {
        "additions": 5,
        "deletions": 0,
        "file": "src/main.js"
      }
    ]
  },
  {
    "refs": [],
    "hash": "3cc6909525a3c7ac229c076eda2ba14cf7d183c5",
    "hashAbbrev": "3cc6909",
    "tree": "9b8fd6ad6d76aa915cc8488a5a3184e4567a568c",
    "treeAbbrev": "9b8fd6a",
    "parents": [],
    "parentsAbbrev": [],
    "author": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1597996890000
    },
    "committer": {
      "name": "Li Zihao",
      "email": "lizihao@springup.xyz",
      "timestamp": 1597996890000
    },
    "subject": "init",
    "body": "",
    "notes": "",
    "stats": [
      {
        "additions": 23,
        "deletions": 0,
        "file": ".gitignore"
      },
      {
        "additions": 24,
        "deletions": 0,
        "file": "README.md"
      },
      {
        "additions": 5,
        "deletions": 0,
        "file": "babel.config.js"
      },
      {
        "additions": 11874,
        "deletions": 0,
        "file": "package-lock.json"
      },
      {
        "additions": 42,
        "deletions": 0,
        "file": "package.json"
      },
      {
        "additions": null,
        "deletions": null,
        "file": "public/favicon.ico"
      },
      {
        "additions": 17,
        "deletions": 0,
        "file": "public/index.html"
      },
      {
        "additions": 28,
        "deletions": 0,
        "file": "src/App.vue"
      },
      {
        "additions": null,
        "deletions": null,
        "file": "src/assets/logo.png"
      },
      {
        "additions": 58,
        "deletions": 0,
        "file": "src/components/HelloWorld.vue"
      },
      {
        "additions": 8,
        "deletions": 0,
        "file": "src/main.js"
      }
    ]
  }
]

**Comment by applelizihao** [comment]
I think there is something wrong with the order of branch output. At least a commit should not be submitted. The order of branches has changed
