### ISSUE TITLE
Gitgraph slice paging data display problem

### ISSUE THREAD

**Issue by applelizihao** [nicoespeon/gitgraph.js#381]
Gitgraph slice paging data display problem，When cutting with slice, there is an exception when rendering the graph because the parent node cannot be found
![image](https://user-images.githubusercontent.com/47731529/93036126-8b7a3200-f671-11ea-8238-ce96b9058a6d.png)
Do the great gods have any good solutions!!!

**Comment by nicoespeon** [comment]
Hi @applelizihao 👋 

Sorry, I don't have much context anymore, but it reminds me about these workarounds that may work for you:
- https://github.com/nicoespeon/gitgraph.js/issues/215#issuecomment-486700869
- https://github.com/nicoespeon/gitgraph.js/issues/277#issuecomment-514092217

Hope these could help!
