### ISSUE TITLE
Deleting branches does not work

### ISSUE THREAD

**Issue by Marty** [nicoespeon/gitgraph.js#388]
**Describe the bug**

`branch.delete()` does nothing

**To Reproduce**

Code for https://codepen.io/nicoespeon/pen/arqPWb?editors=0010

```
const graphContainer = document.getElementById("graph-container");
 
// Instantiate the graph.
const gitgraph = GitgraphJS.createGitgraph(graphContainer);

// Simulate git commands with Gitgraph API.
const master = gitgraph.branch("master");
master.commit("Initial commit");

var feature = master.branch("feature");
feature.commit("a");
master.merge(feature);
feature.delete();
```
Branch "feature" is still visible.

**Expected behavior**

The ref "feature" should be gone.

**Screenshots**

n/a

**Context**

`@gitgraph/js`

**Comment by nicoespeon** [comment]
@all-contributors please add Marty for ideas
