### ISSUE TITLE
React.StrictMode breaks the horizontal text alignments

### ISSUE THREAD

**Issue by ncortines** [nicoespeon/gitgraph.js#389]
Hi,

first of all sorry for the low effort bug report - I'll provide more details on request but I found the issue quite straightforward to reproduce.

When wrapping the react component with **React.StrictMode**, all the text horizontal alignments are broken.

Basically the translate(x) alignments are double compensated with a second translate(-x), leaving them all left aligned with the surrounding container.

Easy workaround is of course remove React.StrictMode form the application.

Thanks,
Juan

**Comment by crutchcorn** [comment]
A minimal reproduction of this issue is here:

https://github.com/crutchcorn/graphjs-strict-bug

I'll be taking a look at this to see if I can't just make a PR right now
