### ISSUE TITLE
More template options for author rendering  -  easy feature

### ISSUE THREAD

**Issue by Iftahh** [nicoespeon/gitgraph.js#397]
**Is your feature request related to a problem? Please describe.**
In my use case author email isn't necessary (we have a small team, everyone knows each other by name)
also, I'd like to highlight the message and mute a bit the author name.

**Describe the solution you'd like**
I want template options for the author rendering - eg. hide email and change author font/color

**Describe alternatives you've considered**
I solved it by supplying a custom renderMessage function - but this simple change should be easier.

**Additional context**
The render function I wrote:

```
function renderMessage(commit) {
      const messageElement = document.createElementNS("http://www.w3.org/2000/svg", "text");
      messageElement.setAttribute("transform", `translate(0, ${commit.style.dot.size})`);
      messageElement.setAttribute("fill", `${commit.style.message.color}`);
      messageElement.setAttribute("style", `font: ${commit.style.message.font}`);
      messageElement.setAttribute("alignment-baseline","central")
      messageElement.setAttribute("dominant-baseline","central")
      messageElement.innerHTML = `<tspan>${commit.subject} - </tspan><tspan fill="#A7B7C7">${commit.author.name}</tspan>` ; /* add to tspan x=0 dy=20 for new line */
      return messageElement;
    }
```
This is what it looks like:
![flow-explorer](https://user-images.githubusercontent.com/798544/102340985-7c1fc300-3f97-11eb-8c32-a844b3f73f4e.png)

**Comment by FGIKCM** [comment]
+1
An other solution for the email should be to avoid displaying the `' - < ... >'` part if the mail is null / empty in the base renderer.
