### ISSUE TITLE
The merge method does not read commit options

### ISSUE THREAD

**Issue by LeonardVertighel** [nicoespeon/gitgraph.js#412]
**Describe the bug**

When use merge command, the commit options passed to the method are not read correctly

**To Reproduce**

With the online playground (https://codepen.io/nicoespeon/pen/arqPWb?editors=0010) use the code below in the js tab.
```
const graphContainer = document.getElementById("graph-container");

const dev1 = "dev1 <dev1@company.com>";
const dev2 = "dev2 <dev2@company.com>";
const dev3 = "dev3 <dev3@company.com>";

const config = {
                 template: "blackarrow"
                ,orientation: "vertical"
                 //,orientation: "horizontal"
                 //,orientation: "vertical-reverse"
               };

const gitgraph = GitgraphJS.createGitgraph(graphContainer, config);

const master = gitgraph.branch({name: "master"})
.commit({subject: "Project created",author: dev1})
.commit({subject: "First module completed",author: dev1});

const branch1 = gitgraph.branch({name :"branch1", from: master})
.commit({subject: "Second module started", author: dev2});

master.commit({subject: "Third module completed", author: dev1});

const branch2 = gitgraph.branch({name: "branch2", from: master})
.commit({subject: "Fourth module started", author: dev3})
.commit({subject: "Fourth module optimized", author: dev3})
.commit({subject: "Fourth module completed", author: dev3});

branch1.merge(branch2, {subject: "Integrate fourth module", author: dev2})
.commit({subject: "Second module completed", author: dev2});

master.merge(branch1, {subject: "Software released", author: dev1}).tag("v1.0.0");

```

The subject and the author passed to the merge command are not used:
![image](https://user-images.githubusercontent.com/45466797/133983933-1ead935e-85fa-4df3-9ffa-846792b89106.png)

- library: I think @gitgraph/js, but I am not sure
- version of the library: I think the last but I am not sure
- browser and version is impacted: Firefox 92.0
- operative system: windows 10

**Comment by fabien0102** [comment]
Hi @LeonardVertighel,

You need to use the "advanced" format for this:
https://github.com/nicoespeon/gitgraph.js/blob/9239bab87f6f00dc4c5da1d1f5b3efec47827748/packages/gitgraph-core/src/user-api/branch-user-api.ts#L14-L27

So with your example:
```diff
   .commit({ subject: 'Fourth module completed', author: dev3 })
 
 branch1
-  .merge(branch2, { subject: 'Integrate fourth module', author: dev2 })
+  .merge({
+    branch: branch2,
+    commitOptions: { subject: 'Integrate fourth module', author: dev2 },
+  })
   .commit({ subject: 'Second module completed', author: dev2 })
 
 master
-  .merge(branch1, { subject: 'Software released', author: dev1 })
+  .merge({
+    branch: branch1,
+    commitOptions: { subject: 'Software released', author: dev1 },
+  })
   .tag('v1.0.0')
```

For reference, the signature of `.merge`:
https://github.com/nicoespeon/gitgraph.js/blob/9239bab87f6f00dc4c5da1d1f5b3efec47827748/packages/gitgraph-core/src/user-api/branch-user-api.ts#L167-L186

The notation you used was giving an object as `subject` so resulting in a `[object Object]` as output 😉

**Comment by LeonardVertighel** [comment]
Thank you for the answer, with the advanced format all works.

If the advanced method is the right way, I think the information at merge section in https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-js/MIGRATE_FROM_GITGRAPH.JS.md needs to be changed: in v2 there is wrote no needs of advanced version.

**Comment by fabien0102** [comment]
Good catch!
