### ISSUE TITLE
Is there a way to set a default author for a branch?

### ISSUE THREAD

**Issue by stratosgear** [nicoespeon/gitgraph.js#414]
My attempts to set a default author per branch seem to fail:

https://codepen.io/stratosgear/pen/JjryMvE?editors=1010

My assumption and what I would expect to work is that all commits on the `a-feature` branch to be done by the `anotherUser`.

I could manually set the author for each separate commit (as done in the third commit) but  that's "too much work"!

Is there another way to do what I want?

Thanks for a great library, btw...

**Comment by fabien0102** [comment]
Indeed, this should do the trick (https://github.com/nicoespeon/gitgraph.js/blob/master/packages/gitgraph-core/src/user-api/gitgraph-user-api.ts#L53) but we may have a little bug over there, do you want to have a look?

**Comment by stratosgear** [comment]
Hey, thanks for pointing to the exact source place, but I took a look at the code and, sorry, I cannot follow through the interface/abstraction layers there, so I'm afraid I cannot be of use... :(
