### ISSUE TITLE
Can not make graph responsive in gitgrap react 1.6.0

### ISSUE THREAD

**Issue by mikevd92** [nicoespeon/gitgraph.js#418]
**Describe the bug**

The "responsive:true" option is missing from gigraph/react and is not mentioned in the storybooks.
How can I make my gitgraph responsive in React?
@nicoespeon @fabien0102  please help!

**To Reproduce**

Add responsive: true to options

**Expected behavior**

Should make graph fill parent

**Context**

- Impacted libraries  `@gitgraph/react`
- gitgraph react 1.6.0
- All browsers

**Additional information**

**Comment by nicoespeon** [comment]
Hey @mikevd92 👋 

This feature was only implemented for `@gitgraph/js` in #303. However, you can get inspired from the fix (https://github.com/nicoespeon/gitgraph.js/commit/8e7d25d713087ea7907a596a58eb116143dba7dd) to make it work in `@gitgraph/react` too.

I don't really have time to dig into this now. If that fix is important to you and your project, I would recommend forking the library so you have full control of the source code. As you can see, there is no active maintainer anymore, so you'd better fork the repo to not be blocked in making the changes you need 😉

**Comment by mikevd92** [comment]
Thanks Nicolae Carlo I have already found
a fix for gitgraph react based on your PR and I’ve forked the repo.

Trimis din Yahoo Mail pentru iPhone


La marți, mai 10, 2022, 3:46 p.m., Nicolas Carlo ***@***.***> a scris:




Hey @mikevd92 👋
 
This feature was only implemented for @gitgraph/js in #303. However, you can get inspired from the fix (8e7d25d) to make it work in @gitgraph/react too.

I don't really have time to dig into this now. If that fix is important to you and your project, I would recommend forking the library so you have full control of the source code. As you can see, there is no active maintainer anymore, so you'd better fork the repo to not be blocked in making the changes you need 😉

**Comment by crutchcorn** [comment]
@mikevd92 If you make a PR I can review, merge, and publish if that's helpful
