### ISSUE TITLE
Highlight the specific word in the line. 

### ISSUE THREAD

**Issue by johnjw12** [nicoespeon/gitgraph.js#428]
can we highlight a word in the line. 

" Adding new feature in my "gitgraph" --> bold (gitgraph)

**Comment by johnjw12** [comment]
@nicoespeon @fabien0102, could you please check

**Comment by nicoespeon** [comment]
Hey @johnjw12 👋 

We are not maintaining this lib anymore, so I may be rusty to help here.
I'm also not sure which lib (js, react) and version you are using. But I remember you can pass custom renderers.

Examples with gitgraph-js: https://github.com/nicoespeon/gitgraph.js/blob/c52e64e81966c22cb024f69a2fd64335ea0c67e6/packages/stories/src/gitgraph-js/6-custom-renders.stories.tsx#L156

Examples with gitgraph-react: https://github.com/nicoespeon/gitgraph.js/blob/c52e64e81966c22cb024f69a2fd64335ea0c67e6/packages/stories/src/gitgraph-react/6-custom-renders.stories.tsx#L115

Therefore, you should be able to highlight and customize what's being rendered as you like!
