### ISSUE TITLE
I can't import @gitgraph/js in next.js project

### ISSUE THREAD

**Issue by saanny** [nicoespeon/gitgraph.js#436]
When i import `@gitgraph/js` library in next.js, I get this error

```
export * from "./gitgraph";
^^^^^^

SyntaxError: Unexpected token 'export'
```
![Screenshot 2023-05-01 124043](https://user-images.githubusercontent.com/20244193/235433410-671a378c-ef73-4fbf-a167-34fe84a9d033.png)

**Comment by oYo-fr** [comment]
Same here in a type script project
