### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by pomeh** [nicoespeon/gitgraph.js#44]
I just discovered your library, and I really like it :)

Here are some suggestions:
- [x] Add link to website http://gitgraphjs.com/ in the main GithHub repository page ([in this page](https://github.com/nicoespeon/gitgraph.js), next to Description)
- [x] Add link to the GitHub repository in the project page ([in this page](http://gitgraphjs.com/))
- [x] Add screenshot next to all code examples in the project's main page (http://gitgraphjs.com/)

Also, based on what's present in the CONTRIBUTING.md file:
- [ ] Add [JavaScript Code Style Checker](https://github.com/jscs-dev/node-jscs) in the grunt workflow
- [ ] Add [csscomb.js](https://github.com/csscomb/csscomb.js) in the grunt workflow

**Comment by nicoespeon** [comment]
Created independent issues for what's left :smiley:
