### ISSUE TITLE
Show markers on commits

### ISSUE THREAD

**Issue by MatthiasLohr** [nicoespeon/gitgraph.js#55]
It would be a really nice feature if there's a option for adding permanently visible labels to commit points - e.g. for displaying tag names etc. It would be important not to have to use mouse over for showing the information (e.g. for presentations and other kinds of non-interactive stuff).

Best regards
Matthias

**Comment by nicoespeon** [comment]
Hi @MatthiasLohr!

Thanks for the feedback.

I guess you're talking about the `"compact"` mode in which tooltips are displayed with commit information when mouse is over. 

Then, does the `"extended"` mode fills your need? It displays commit messages / authors / hash permanently. However, the graph is a bit "longer", but that's may be a question of template only.

**Comment by MatthiasLohr** [comment]
Hey,

no, ```extended```/```compact``` mode is not what i mean. In ```extended``` mode *all* labels are shown (btw: not in ```horizontal``` orientation). What i need is something like (git) tags, for labeling only some special commits.

I'm using gitgraph.js in a reveal.js slideshow for introducing git in developer teams and sometimes it would be really helpful to annotate single commits with "this is the current HEAD" or "this is the merge commit" or something like that.

My JS knowledge is very limited, so i i'm not a great help implementing this feature... sry :(

**Comment by nicoespeon** [comment]
Hi @MatthiasLohr,

Yep I understand what you need, and yep there is no workaround for now.

That could be a useful feature for non-interactive presentations indeed, I'd find something for that. Thanks a lot for the feedback =)

**Comment by nicoespeon** [comment]
Hi @MatthiasLohr !

With the new tag system is addressing your request. You could tag any commit with `myBranch.commit( { message: "My message", tag: "my-tag" } )`.
Works for merge commit too -> `feature.merge( master, { tag: "v1.1.0 } )`.

Let me know if that's good for you. Feel free to re-open if not ;-)
