### ISSUE TITLE
Give options for arrow to point parents instead of children

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#58]
We decided to make arrow point children commit to illustrate the timeline.

However, for educative purpose — and better semantics — it's certainly better for the arrow to point the parent, so we illustrate the dependency.

**Comment by nicoespeon** [comment]
Actually, this was already planned with #46 \o/

**Comment by julenpardo** [comment]
Hi @nicoespeon, how do I activate this option? I've tried with `-reverse`, but this is just for the mirror effect, right?

I'm with v1.2.0 version.

**Comment by larshp** [comment]
Try "reverseArrow: true"

See commit https://github.com/nicoespeon/gitgraph.js/commit/9cd3a9221e4f00752721c797501f82d58333e6b5

**Comment by julenpardo** [comment]
Hi @larshp, thanks for your quick response.

Worked like a charm, many thanks!

**Comment by nicoespeon** [comment]
Thanks @larshp for your reactivity =)
