### ISSUE TITLE
Add method to add tags

### ISSUE THREAD

**Issue by mekwall** [nicoespeon/gitgraph.js#59]
It would be great if we could add tags that are visually different from commits.

**Comment by nicoespeon** [comment]
That could be a great idea indeed =)

**Comment by vnavarro** [comment]
@nicoespeon I added a PR with a proposed solution for this feature :smile:

**Comment by nicoespeon** [comment]
Awesome @vnavarro :+1: 

I'll take a closer look at it within the next days and will let you know.

**Comment by nicoespeon** [comment]
Implemented with #71
