### ISSUE TITLE
vertical-reverse does not seem to work.

### ISSUE THREAD

**Issue by dervalp** [nicoespeon/gitgraph.js#60]
I have tried to use the orientation 'vertical-reverse' for this example (https://github.com/nicoespeon/gitgraph.js/blob/develop/examples/index.html) but nothing is displaying? 

Any idea?

**Comment by nicoespeon** [comment]
Hi @dervalp!

That's strange cause it seems to work here. How did you try that?
Technically, modifying 

```
```
https://github.com/nicoespeon/gitgraph.js/blob/develop/examples/index.js#L29-L32

into 

```
var config = {
  orientation: "vertical-reverse",
  template: "metro" 
};
```

should do the trick.

**Comment by nicoespeon** [comment]
I'm pretty confident this works with last merged PR. Feel free to re-open if you see any bug :wink:
