### ISSUE TITLE
Enable events on commits

### ISSUE THREAD

**Issue by cedricms** [nicoespeon/gitgraph.js#61]
I hope haven't missed the feature, but I'd like to be able to add events on clicks on commits (be it left or right clicks).

The idea is to be able to show the diff of the commit in another view, or bring up a menu that enables a checkout, ...

**Comment by terhechte** [comment]
I've created a pull request for onClick events on commits here: https://github.com/nicoespeon/gitgraph.js/pull/76

Cheers!

**Comment by cedricms** [comment]
Thank you very much :) !

**Comment by nicoespeon** [comment]
Thanks @terhechte so much for this feature by the way.

You can attach a `onCommit` callback to any commit. It takes the clicked `commit` object as parameter:

```
myBranch.commit( {
  message: "Click me!",
  author: "terhechte <you-rock@gmail.com>",
  onClick: function ( commit ) {
    console.log( "You just clicked this commit.", commit );
  }
} );
```
