### ISSUE TITLE
Add option to display branch names at the top

### ISSUE THREAD

**Issue by timlegrand** [nicoespeon/gitgraph.js#66]
hi, it would be great to have a config option display branch name at branch start or current state.
I can't make it print "master" or "develop" at this time.

Great work anyway!
Thanks

**Comment by nicoespeon** [comment]
Hi @timlegrand,

Yep, that could be useful and quite easy to achieve. 
Thanks for the feedback ;-)

**Comment by timlegrand** [comment]
I created a pull request as a first step for that purpose: #69
Next step is to add a `nameOnTop` option for branches and render it. Working on it.

**Comment by nicoespeon** [comment]
Merged your PR :+1: 

Do you wish to keep this issue open or do we plan a "Give option to display branch name on top" enhancement for later?

**Comment by timlegrand** [comment]
I'd go for the option (I already started the code) if you want.

2015-06-22 8:15 GMT+02:00 Nicolas Carlo <notifications@github.com>:
