### ISSUE TITLE
Refactor the way we create tag to add a `.tag()` command

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/gitgraph.js#75]
You can tag any commit using `.commit( { message: "My message", tag: "a-super-tag" } )`.

If we want to mimic the way we use git, we'd rather commit, then tag. Well that's the idea, it would be nice to get a `.tag( "a-super-tag" )` command to tag current HEAD — that would be a good start.

See: https://github.com/nicoespeon/gitgraph.js/pull/74

**Comment by lucasvc** [comment]
Yes, it is a good idea!
I've done two things, depending the sitation:

````
var release1 = develop.branch("release/1_branch");
release1.parentCommit.tag = "release/1_01";
````
````
release1.commit();
release1.commits[release1.commits.length - 1].tag = "release/1_02";
````
