### ISSUE TITLE
Details are not displayed when orientation is "vertical-reverse"

### ISSUE THREAD

**Issue by thombergs** [nicoespeon/gitgraph.js#81]
When I set the orientation of a git graph to "vertical-reverse" the details I specified via the "detailId" option are no longer displayed. When I switch back to "vertical" the details are displayed again.

**Comment by nicoespeon** [comment]
Actually this is not a bug but a lack of implementation as you can see here: https://github.com/nicoespeon/gitgraph.js/commit/e7368374

I updated the label to illustrate the enhancement requirement.
Thanks for pointing out the need.

**Comment by nicoespeon** [comment]
Shipped in [v1.8.2](https://github.com/nicoespeon/gitgraph.js/releases/tag/v1.8.2).
