### ISSUE TITLE
Non-ascii characters not encoding properly

### ISSUE THREAD

**Issue by julenpardo** [nicoespeon/gitgraph.js#82]
Hi,

I'm spanish and I'm dealing everytime with extrange characters (ñ, á, é, etc.). And I've noticed that this chars are not displayed correctly in the render, .e.g, in commit messages.

Thank you and congrats for your work.

**Comment by nicoespeon** [comment]
Hi @julenpardo!

Thanks for reporting, I'll have a look at this encoding issue ;)

**Comment by julenpardo** [comment]
Hi @nicospeon, 
It was my fault; I didn't set properly page's encoding.

Sorry for the inconvenience.

**Comment by nicoespeon** [comment]
No problem, glad to hear that your problem is solved :+1:
