### ISSUE TITLE
Details displayed too far on the left

### ISSUE THREAD

**Issue by mksplg** [nicoespeon/gitgraph.js#85]
Since commit f61f29b1b21d69c52b75069f78622c8f8070ec86, details are not positioned with the same indentation as the commit messages.

This can be seen in the [example](https://github.com/nicoespeon/gitgraph.js/blob/develop/examples/index.html) (after fixing #84 :)).

**Comment by potherca** [comment]
This can also be seen in the following screenshot :wink: 
<img width="1098" alt="screen shot 2015-12-27 at 21 07 19" src="https://cloud.githubusercontent.com/assets/195757/12011799/e390be6a-acdd-11e5-85fb-716213d9de65.png">
