### ISSUE TITLE
Branch from a previous commit

### ISSUE THREAD

**Issue by Martin1994** [nicoespeon/gitgraph.js#86]
These codes won't work properly:
 ````javascript
var graph = new GitGraph();
var master = graph.branch("master");
var branch = master.branch("branch");
master.commit();
branch.commit();
````

Should looks like this:
````
o--o
 \----o
````

But looks like this:
````
o--o
    \-o
````

**Comment by orao** [comment]
I would like to provide an additional use case for this issue. _Though not standard git flow I do have a need for this funky merge type in my [ac2git](https://github.com/orao/ac2git) conversion._ The following is an [example of the incorrect rendering](http://jsfiddle.net/guan1oz1/468/), while I would expect it to look something like [this workaround](http://jsfiddle.net/guan1oz1/470/).

Additionally, there is one more problem that occurs when I want to swap the order of the merge. Once again, the [incorrect rendering example](http://jsfiddle.net/guan1oz1/472/) and the [workaround](http://jsfiddle.net/guan1oz1/473/).

If I get time I will take a look at these specific problems and provide a patch but it probably won't happen this week.
