### ISSUE TITLE
More rendering control

### ISSUE THREAD

**Issue by Martin1994** [nicoespeon/gitgraph.js#87]
Here are some suggestions:

1. Expose pixel ratio or unscaled resolusion. I need to draw `GitGraph` into another canvas, but the style attribute may be changed by other codes.

2. Add `ondraw` event.

**Comment by nicoespeon** [comment]
Hi @Martin1994!

Thanks for the suggestions & other bug reports / PRs.

Will have a look on all of this as soon as I can :smiley:

**Comment by nicoespeon** [comment]
Hi @Martin1994,

I'm adding all this to GitGraph but I'd need some clarification about your first point: would it be useful to *know* the scale ratio or to be able to *override* it? Hence, would you rather deal with the scale ratio or the unscaled resolution?

Thanks for your feedbacks =)

**Comment by Martin1994** [comment]
Hi @nicoespeon ,

Knowing the scale ratio is enough. Maybe it's a good idea to add a parameter in the constructor, but no need to mutate it.

I need to draw it into another canvas. Thus I need to know the dimensions in virtual pixels. With this feature, I think it will be easier to use `GitGraph` with other canvas libraries on high-res devices.
