### ISSUE TITLE
Support for commit:mouseout

### ISSUE THREAD

**Issue by bpatra** [nicoespeon/gitgraph.js#97]
There is an event *commit:mouseover* that is emited by the gitgraph.js code when the mouse is over a commit.
See the following example where we change the mouse cursor when the mouse enters a commit
```
 gitGraph.canvas.addEventListener("commit:mouseover", function (event) {
                this.style.cursor = "pointer";
 });
```
Similarly it will be useful to have a *commit:mouseout* event. For example, this can be used to change the mouse cursor when hovering a commit.

```
gitGraph.canvas.addEventListener("commit:mouseover", function (event) {
    this.style.cursor = "pointer";
});
gitGraph.canvas.addEventListener("commit:mouseout", function () {
    this.style.cursor = "auto";
});
```

**Comment by nicoespeon** [comment]
Hi @bpatra and thanks for this useful proposition.

Works like a charm, it will be part of the next release :+1:
